### ISSUE TITLE
 std::unique_ptr<Reader> nycReader2 = makeUnique<Reader>(outPath + "n", tmpPath, *cache); The program has unexpectedly finished.

### ISSUE THREAD

**Issue by zhan520** [connormanning/entwine#101]
![image](https://user-images.githubusercontent.com/12770958/42211891-39919a72-7ee7-11e8-99ca-a65d9ee25824.png)After I debug, I found the mistake probably in this position, there is an error in the for loop, but I don't know yet what the data, I will continue to debug, if you also have encountered the problem and the solution, would you please tell me, I will be very grateful to you

**Comment by connormanning** [comment]
Can you try the new codebase from `master` now that #98 has been merged.
