### ISSUE TITLE
ept branch is not, can you give me an ept branch code?

### ISSUE THREAD

**Issue by zhan520** [connormanning/entwine#105]
![image](https://user-images.githubusercontent.com/12770958/42485285-93a4ee28-8429-11e8-80c6-bc7ada5f5972.png)

**Comment by connormanning** [comment]
As stated both [here](https://github.com/connormanning/entwine/issues/102) and [here](https://github.com/connormanning/entwine/issues/101) to your own submitted issues within the past week, **follow the readme**, which has no mention of an `ept` branch nor of Greyhound.
