### ISSUE TITLE
Can't display any indexed point with greyhound

### ISSUE THREAD

**Issue by ToHold** [connormanning/entwine#106]
Hello, I finally succeeded to index my .laz with entwine, and now I'd like to use greyhound to display them on potree or speckly.

This is the commands that I've used to index (this is working fine) : 
`sudo docker run -it -v /home/entwine:/home/entwine connormanning/entwine build    -i /home/entwine/input/pointcloud.laz    -o /home/entwine/output/PointCloud -b "[-1900000, -1900000, -1900000, 1900000, 1900000, 1900000]"`

But once this is done, when I try to start greyhound, i got this error message : 
(the command used to start) : 
`sudo docker run -it -v $HOME/entwine/output:/opt/data -p 8080:8080 connormanning/greyhound`

(the error message when i go on : http://speck.ly/?s=http://localhost:8080/&r=entwine)
```
sudo docker run -it -v $HOME/entwine/output:/opt/data -p 8080:8080 connormanning/greyhound
Using default config
Settings:
	Cache: 209715200 bytes
	Threads: 4
	Resource timeout: 2 minutes
	Tmp dir: /tmp
Paths:
	/greyhound
	~/greyhound
	/entwine
	~/entwine
	/opt/data
Headers:
	Access-Control-Allow-Methods: GET,PUT,POST,DELETE
	Access-Control-Allow-Origin: *
	Cache-Control: public, max-age=300
Writes NOT allowed
Static serve:
	/usr/include/greyhound/public
Listening:
	HTTP: 8080
Creating entwine
	Trying /greyhound: fail - Could not read file /greyhound/entwine/entwine
	Trying ~/greyhound: fail - Could not read file /root/greyhound/entwine/entwine
	Trying /entwine: fail - Could not read file /entwine/entwine/entwine
	Trying ~/entwine: fail - Could not read file /root/entwine/entwine/entwine
	Trying /opt/data: fail - Could not read file /opt/data/entwine/entwine
Exception in pool task: Not found: entwine
Creating entwine
	Trying /greyhound: fail - Could not read file /greyhound/entwine/entwine
	Trying ~/greyhound: fail - Could not read file /root/greyhound/entwine/entwine
	Trying /entwine: fail - Could not read file /entwine/entwine/entwine
	Trying ~/entwine: fail - Could not read file /root/entwine/entwine/entwine
	Trying /opt/data: fail - Could not read file /opt/data/entwine/entwine
HTTP error: Not found: entwine

```

Can you please help me, this would be appreciated

**Comment by connormanning** [comment]
Please follow Entwine's readme/documentation, which does not involve Greyhound.  I will update Greyhound's readme (which I assume is what you are following to run into this issue) to indicate this as well.

**Comment by ToHold** [comment]
Alright I'll check for the greyhound readme's update then, but could you tell me what to do to resolve this issue.

**Comment by connormanning** [comment]
Please follow Entwine's readme/documentation: https://github.com/connormanning/entwine

**Comment by connormanning** [comment]
I've updated Greyhound's readme to indicate this workflow change.
