### ISSUE TITLE
Bounds are too large for the selected scale

### ISSUE THREAD

**Issue by RaidCode** [connormanning/entwine#107]
Hello , i encounter this issue when i build :
```
EntWine    | Scanning input
EntWine    | 1 / 1: /input/test.laz
EntWine    | Correcting malformed Bounds
EntWine    | Maximal extents: [(-2147483648, -2147483648, -2147483648), (2147483647, 2147483647, 2147483647)]
EntWine    | Scaled bounds:   [(-9223372036854775808, -9223372036854775808, -9223372036854775808), (-9223372036854775808, -9223372036854775808, -9223372036854775808)]
EntWine    | Encountered an error: Bounds are too large for the selected scale
EntWine    | Exiting.
```
What is the best way to correct it ?

Thank for your assistance

**Comment by connormanning** [comment]
You could also try running with `--noTrustHeaders`.

**Comment by cherukumilli** [comment]
@connormanning 
I am seeing the same problem when I run the following command on the 

```

**Comment by connormanning** [comment]
Oops, I had accidentally copied the wrong version of that file (one without an SRS) to that path.  I've updated it.  Please try again, @cherukumilli.

**Comment by RaidCode** [comment]
Hey, i've try with, `--noTrustHeaders` no change about my issue.
I upload my laz for you here : https://filebin.net/1rdwsuls5hkv35t8/test.laz?t=66rkno5c

**Comment by connormanning** [comment]
@RaidCode, I see now that that flag isn't working quite properly - will fix.  The root cause it that your file has a bad header, from `pdal info`:
```
      {
        "name": "X",
        "minimum": 1412157.49,
        "maximum": 1412297.964
      }, {
        "name": "Y",
        "minimum": 4182540.495,
        "maximum": 4182670.685
      }, {
        "name": "Z",
        "minimum": 89.25269658,
        "maximum": 100.8826966
    }
```

However your metadata has no bounds information, from `pdal info --metadata`:
```
    "maxx": 0,
    "maxy": 0,
    "maxz": 0,
    "minx": 0,
    "miny": 0,
    "minz": 0,
```

In the meantime until `--noTrustHeaders` is fixed, you can manually enter the bounds during `entwine build`.  I successfully built your file by adding :
```
-b "[1412157.49, 4182540.495, 89.25269658, 1412297.964, 4182670.685, 100.8826966]"
```

**Comment by connormanning** [comment]
I've fixed that issue, so you should be able to use the `--noTrustHeaders` flag with the expected successful results.  However I do recommend that you fix your file headers as part of your data acquisition process.

**Comment by RaidCode** [comment]
@connormanning Thank you very much, i will test 👍 
i've an other question about Entwine :
Have you updated your docker version ? After fixed this issue 💡
