### ISSUE TITLE
 Unable to create open stream for '/opt/data/abc.laz'

### ISSUE THREAD

**Issue by elfayoumi** [connormanning/entwine#11]
Hello
I have Ubuntu trusty, 14.04, with docker.io and tried to follow the suggested method to try the repository: 
 docker run -it -v $HOME:/opt/data connormanning/entwine     entwine build -i /opt/data/abc.laz -o /opt/data/entwine/abc

I received an error: 
Performing dataset inference...
1 / 1: /opt/data/abc.laz
Exception caught in pool task: Unable to create open stream for '/opt/data/abc.laz' with error 'No such file or directory'
Encountered an error: Zero points found
Exiting.
gcc@gcc:~/bin$ docker run -it -v $HOME:/opt/data connormanning/entwine     entwine build -i /opt/data/abc.laz -o /opt/data/entwine/abc
Performing dataset inference...
1 / 1: /opt/data/abc.laz
Exception caught in pool task: Unable to create open stream for '/opt/data/abc.laz' with error 'No such file or directory'
Encountered an error: Zero points found
Exiting.

why could not load the abc.laz?

Regards
Ibrahim

**Comment by connormanning** [comment]
Entwine's repository doesn't ship with any sample data - so `abc.laz` is only meant as an example name.  For this exact command to work, you'd need a file at `~/abc.laz` file on your local filesystem.

If you want to index a file at `~/point-clouds/testing.laz`, your build command would be `-i /opt/data/point-clouds/testing.laz`, for example.

**Comment by elfayoumi** [comment]
thanks-------- Original Message --------Subject: Re: [connormanning/entwine] Unable to create open stream for '/opt/data/abc.laz' (#11)From: Connor Manning To: connormanning/entwine CC: elfayoumi ,Author Entwine's repository doesn't ship with any sample data - so abc.laz is only meant as an example name.  For this exact command to work, you'd need a file at ~/abc.laz file on your local filesystem.

If you want to index a file at ~/point-clouds/testing.laz, your build command would be -i /opt/data/point-clouds/testing.laz, for example.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/connormanning/entwine","title":"connormanning/entwine","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/connormanning/entwine"}},"updates":{"snippets":[{"icon":"PERSON","message":"@connormanning in #11: Entwine's repository doesn't ship with any sample data - so `abc.laz` is only meant as an example name.  For this exact command to work, you'd need a file at `~/abc.laz` file on your local filesystem.\r\n\r\nIf you want to index a file at `~/point-clouds/testing.laz`, your build command would be `-i /opt/data/point-clouds/testing.laz`, for example."}],"action":{"name":"View Issue","url":"https://github.com/connormanning/entwine/issues/11#issuecomment-247214472"}}}
