### ISSUE TITLE
Fail PUT attempts to S3 during entwine build - how to enable SSE? 

### ISSUE THREAD

**Issue by wakruse** [connormanning/entwine#112]
My S3 environment requires SSE enabled for writing. The Docker entwine build command works on ec2 local disks but generates failed PUT attempts when writing to S3. My assumptions is that this error is due to the SSE requirement since the build works until it starts to index the first few tiles and write the results.

Could you suggest the recommended way to enable SSE writes when using entwine/arbiter in Docker? I've tried setting the entwine build arbiter configure option in a validated json file but may not have used the correct syntax or information.

JSON build config file contents: {"arbiter":{"sse":"True"}}

**Comment by connormanning** [comment]
Can you try in your config:
```
{ "arbiter": {  "s3": { "sse": true } } }
```

**Comment by wakruse** [comment]
Thanks Conner, that works. It would be great to have a little more documentation or a few examples on using the json configuration options not covered by the command line flags.

**Comment by connormanning** [comment]
I've added a bit of documentation [here](https://github.com/connormanning/entwine/blob/bff5abeee5800ec98320243ef8da7206af616a40/doc/configuration.md#common).
