### ISSUE TITLE
Numpy Missing in Latest Docker Image

### ISSUE THREAD

**Issue by ProjectBarks** [connormanning/entwine#114]
When you try to run entwine this comes up repeatedly
```Exception in pool task: ImportError('No module named numpy',)```

Here is information about my image:
https://pastebin.com/j8tj1884

**Comment by ProjectBarks** [comment]
It looks like pdal purges numpy when it should be kept https://github.com/PDAL/PDAL/blob/master/scripts/docker/ubuntu/Dockerfile#L63

**Comment by ProjectBarks** [comment]
Created a related PR https://github.com/PDAL/PDAL/pull/2091

**Comment by connormanning** [comment]
Fixed in 8d1b76329cc98a9300132d531284e4e27c79e2fb
