### ISSUE TITLE
Using DigitalOcean Spaces (S3 object storage compatible service)

### ISSUE THREAD

**Issue by pyarza** [connormanning/entwine#120]
First of all, thank you @connormanning  for your amazing job with this tool to generate pointcloud octrees.

I'm trying to work with the [DigitalOcean Spaces](https://www.digitalocean.com/products/spaces/) (an S3 compatible object storage service) backend as the source for the LAS/LAZ files and also as the destination for the entwine EPT octree files. I have found some minor issues and you may be able to help with those.

<hr>

**[1]. OUTPUT**. Regarding configuring the DO Spaces as the destination for the octree I haven't found any issues but one:

Because of [the way the DO Spaces assigns default permits](https://www.digitalocean.com/community/questions/how-to-set-file-uploaded-to-publlic-do-spaces): _"You will need to change all of your files to have the 'Public' permission if you'd like them to be world readable, regardless of how you've set your Space permission."_ with my current knowledge of the entwine configuration options, this change on the ACL permits has to be done after upload to the S3 bucket, and it's quite time consuming (I have tried several tools: s3cmd or the DO Spaces web interface) for a large set of files like the one generated by entwine.

So my question would be:

**Is there any way of configuring Arbiter/Entwine (at the config.json file level) so that a header that makes the ACL/permit: public read can be passed along with the octree LAS/LAZ files while being written/uploaded to the S3 backend directly from within the entwine process?**

According to the [AWS S3 REST headers for PUT messages](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUTacl.html#RESTObjectPUTacl-requests) (I believe that this is what is being used inside Arbiter) the following header:

```
x-amz-acl: public-read
```

on the PUT triggered by entwine would store the data on the S3 compatible bucket with the proper ACL settings. (note: I'm using entwine through a docker instance)

<hr>

**[2]. INPUT**. Also, regarding input (reading data from DO Spaces) everything seems to work properly although in my limited tests I have noticed that it is much faster to do the following:

1. Download data to "processing" computer (via s3cmd).
2. Process (run entwine) with **input data coming from a local source** (the downloaded data) and destination (output) to the S3 service.

Than doing everything from and to the S3 storage:

1. Process (run entwine) with **input data coming from S3** service and destination (output) also to the S3 service .

Can you provide any information/suggestions on the advantages/disadvantages of either approach? (I know that in order to download the data you have to have enough space on the processing computer)

<hr>

**[3.] Configuration**: Finally just one **note on the configuration** of entwine:

In order to be able to access to the DigitalOcean Spaces infrastructure the endpoint variable has to be configured in the arbiter section of the `config.json` file with something like this:

```
"arbiter": {
  "s3": {
    "profile":"default",
    "endpoint": "ams3.digitaloceanspaces.com",
    "access":"access",
    "secret":"secret"
  }
}
```

I haven't been able to find any mention to the endpoint explained in the [arbiter section of the documentation](https://github.com/connormanning/entwine/blob/master/doc/configuration.md#arbiter), but luckily found it through digging on the source code! so it maybe useful to other users.

**Comment by connormanning** [comment]
1. I've added (in a0a54348d65486e29695a5acedb48a33518b87c7) the ability to set a `headers` object in the `arbiter.s3` configuration that will allow you to set arbitrary headers to be sent to S3.  For example, make `acl.json` with contents: 

```
{ "arbiter": { "s3": { "headers": { "x-amz-acl": "public-read" } } } }
```

Then the following should set that header on the way to S3:
```
entwine scan \
    --config acl.json \
    -i https://entwine.io/data/red-rocks.laz \
    -o s3://whatever-bucket/red-rocks.json
```

2. This makes sense because using S3 sources during Entwine causes an entire download of the dataset inline with the Entwine task itself.  If it fits your workflow I don't see a problem with pre-downloading, but I also don't know what type of workflow would be improved by doing this.  For example in EC2 you're still paying for the compute time to download the data locally, so I don't know that `download + locally-index` is actually much cheaper than just `remote-index`.  For subset builds this is also impractical since you'd have to download the entire dataset multiple times, and various subsets would not even need the full dataset so much of that work might be wasted.
So my recommendation is that if it improves your workflow, go ahead and pre-download - but it's never been something that I've personally wanted to do.

3. The hope is that the common flags (like `--profile`, `--sse`, and `--requesterPays` for S3) are enough for almost everyone's use-cases.  However it's certainly accurate that the arbiter documentation within entwine is lacking and could use a few notes on more advanced usage.  Another example of a worthwhile use-case missing appropriate documentation is using multiple profiles, for example reading with different creds than writing.

**Comment by connormanning** [comment]
Oh, actually multiple profile usage is documented already - right below where you linked to the minimal arbiter documentation earlier.  So scratch that specific example, but the point still stands.

**Comment by pyarza** [comment]
Hi @connormanning, thanks for the prompt reply and the updates.

I have tried to pull the latest docker image available:
```
docker pull connormanning/entwine
```
on a clean machine, but it is not working: I'm still getting "private" objects on the destination bucket.

I have tried activating the CURL verbosity: `-e "CURL_VERBOSE=1"` on my call to the entwine docker image (`config.json` has been updated with the `"headers": { "x-amz-acl": "public-read" }`). Whe I run this:
```
docker run --name pyla_ent -d -e "CURL_VERBOSE=1" -v /root/entwine:/entwine  -v /root/entcon:/entcon  connormanning/entwine build -c /entcon/config.json
```
to check what was going on, it seems to me that the headers (`x-amz-acl`) are not being set at all while the other `amz` headers appear to be working. From the log of the entwine run:

```
2018-08-06T17:04:32.344730471Z > PUT /ent/pnoa_h0533_2016_rgb_30f_public/h/0-0-0-0.json HTTP/1.1
2018-08-06T17:04:32.344744762Z Host: sigcar-test.ams3.digitaloceanspaces.com
2018-08-06T17:04:32.344748571Z Accept: */*
2018-08-06T17:04:32.344751213Z Authorization: AWS4-HMAC-SHA256 Credential=727XESHKOMPZTNP4VFSG/20180806/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=9d1159897184ed2394a80a106cf6642195cb52e3712effb38319e1241d353e4f
2018-08-06T17:04:32.344754070Z Content-Type: application/json
2018-08-06T17:04:32.344757326Z X-Amz-Content-Sha256: 95257d8ebc97aaed63fe958bc13875baa1c654944cb426bdf83a42fc655ba998
2018-08-06T17:04:32.344759946Z X-Amz-Date: 20180806T170432Z
2018-08-06T17:04:32.344762293Z Content-Length: 51375
2018-08-06T17:04:32.344764647Z Expect: 100-continue
2018-08-06T17:04:32.344767111Z 
2018-08-06T17:04:32.354946773Z < HTTP/1.1 100 CONTINUE
2018-08-06T17:04:32.354963973Z * We are completely uploaded and fine
2018-08-06T17:04:32.415146982Z < HTTP/1.1 200 OK
```

I'm not sure if you automatically trigger the generation of the new docker images on docker hub or if it is something that you manually trigger once in a while.
Is that the case?
Do I have to wait for a new image to be available?
Or is it easy to build one my self?
Thanks in advance

Thanks also for your updates/clarifications on items [2] & [3]: I will do some more testing in terms of total speed for downloading + processing vs remote-indexing: I'm still at the stage of not doing sub-set builds so that may change my processing setup.

**Comment by connormanning** [comment]
Sorry I forgot to push the image.  Please pull now and try again.

You can also build your own with `cd scripts/docker && docker build -t connormanning/entwine .`

**Comment by pyarza** [comment]
Thanks for the update.Now it works perfectly!

I get the headers (`x-amz-acl: public-read`) properly set:

```
2018-08-06T19:32:55.453321955Z > PUT /ent/pnoa_h0533_2016_rgb_30f_public/entwine-build.json HTTP/1.1
2018-08-06T19:32:55.453324519Z Host: sigcar-test.ams3.digitaloceanspaces.com
2018-08-06T19:32:55.453327041Z Accept: */*
2018-08-06T19:32:55.453329536Z Authorization: AWS4-HMAC-SHA256 Credential=727XESHKOMPZTNP4VFSG/20180806/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-acl;x-amz-content-sha256;x-amz-date, Signature=79068c55cbfc57de4740f38e1fac8f751d00fff3d1a86b7751dd03c7005f0003
2018-08-06T19:32:55.453332381Z Content-Type: application/json
2018-08-06T19:32:55.453334837Z X-Amz-Content-Sha256: 362f8c443927b10f76c8bac1987b0168d0be979c8c8c31c5f9595db377a265bf
2018-08-06T19:32:55.453337378Z X-Amz-Date: 20180806T193255Z
2018-08-06T19:32:55.453339827Z x-amz-acl: public-read
2018-08-06T19:32:55.453342302Z Content-Length: 109
```

And also the ACL are properly set when checking the file attributes on the DO web interface:
<img width="1090" alt="do_spaces_acl_correct" src="https://user-images.githubusercontent.com/1470210/43741383-734a568a-99ce-11e8-8cd8-02eae24b3703.png">

Closing the issue. Thank you.
