### ISSUE TITLE
CMake issue

### ISSUE THREAD

**Issue by Hutch07** [connormanning/entwine#121]
When I try to make this on Windows 10 - Visual Studio 2015,  I get 
`Detecting CXX compile features - done
Defaulting to release mode
Could NOT find JSONCPP (missing: JSONCPP_LIBRARY JSONCPP_INCLUDE_DIR) 
Using system JsonCpp
CMake Error at C:/PDAL-1.7.2/PDALConfig.cmake:11 (message):
  File or directory C:/Program referenced by variable _foo does not exist !
Call Stack (most recent call first):
  C:/PDAL-1.7.2/PDALConfig.cmake:34 (set_and_check)
  CMakeLists.txt:59 (find_package)`

Do I need to find the jsoncpp or update something?

I tried using Entwine with Docker but it kept failing and I'm running out of time.

**Comment by hobu** [comment]
Look at the appveyor.yml for examples of how to configure for windows. It has not been strongly tested on windows and you are likely going to have to work a few small issues there getting it going. 

We also take consulting on these tools if you want direct help on the topic.
