### ISSUE TITLE
lost details at the ground

### ISSUE THREAD

**Issue by wemamawe** [connormanning/entwine#122]
hello connormanning : 
     thank you for build 1.3 version, i used entwine:latest  to build a cesium format project, the size of imput folder is about 100Gb. i done two steps ,build and convert, after builded ,the size of builded folder is about 13Gb. after converted, the size of converted folder is about 24Gb. 
![cesium_entwine_allfiles](https://user-images.githubusercontent.com/29365634/44183316-1445dd00-a13d-11e8-982d-cc7645fdacb2.png) 
                                           ###  file info
![cesium_entwine_xhr_load](https://user-images.githubusercontent.com/29365634/44183332-29227080-a13d-11e8-826a-7422cf5c4956.png)
                                          ###      xhr load process
![cesium_entwine](https://user-images.githubusercontent.com/29365634/44183340-30497e80-a13d-11e8-9a2e-4c71ffb2515c.png)
                                          ### The dispaly of 3dtiles

![cesium_entwine1](https://user-images.githubusercontent.com/29365634/44183540-f75dd980-a13d-11e8-9e79-14f62aaefd27.png)

As you can see, some ground lose points very bad, i can't find the reason , can you explain it?

This is my shell code  

> docker run -it -v /*/*/entwine:/media/entwine connormanning/entwine:ept build --config /*/*/config.json

> docker run -it -v /*/*/entwine:/media/entwine connormanning/entwine:latest convert --input /media/entwine/result --output /media/entwine/cesium/bj_test --threads 8 --colorType "intensity" --truncate --geometricErrorDivisor 16.0

**Comment by connormanning** [comment]
Hard to say - it's possible these points are slightly under the surface of the terrain, but aside from that I have no immediate solution from these screenshots.  How does the initial EPT output look in Potree?  Does it look as you'd expect?

The easiest way for me to help would be for you to share a link to a small portion of the input data that would allow me to reproduce this issue.

**Comment by ProjectBarks** [comment]
This is a cesium issue. Tiles that start at too high of a level end up having a floating point error and converging to one point.

**Comment by connormanning** [comment]
Going to close this one - if you can share some data with me to reproduce the issue (email would be fine if it's not public) I'd take a look.
