### ISSUE TITLE
Error running build with S3 input/output

### ISSUE THREAD

**Issue by mccarthyryanc** [connormanning/entwine#125]
I'm testing out entwine via the docker image and I am getting a driver error:

```bash
sudo docker run -it connormanning/entwine build -v -i s3://bucket/prefix/laz/ -o s3://bucket/prefix/ept/
```

Which outputs:
```
Scanning input
Curl config:
        timeout: 5s
        followRedirect: true
        verifyPeer: true
        caBundle: (default)
        caInfo: (default)
Encountered an error: No driver for s3://bucket/prefix/laz/*
Exiting.
```

Here is the docker image info:
```
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
connormanning/entwine   latest              5399e1f359a3        5 days ago          3.23GB
```

This is running from an EC2 instance, Ubuntu 16.04, that does have access to the S3 bucket in question.

**Comment by connormanning** [comment]
See https://github.com/connormanning/entwine/blob/master/doc/configuration.md#s3

**Comment by mccarthyryanc** [comment]
The EC2 instance is given S3 permissions via an IAM role assignment. Perhaps this is an issue for [Arbiter](https://github.com/connormanning/arbiter/issues/8)?

**Comment by connormanning** [comment]
Try setting the environment variable `AWS_ALLOW_INSTANCE_PROFILE`.  With docker that'll be something like `-e AWS_ALLOW_INSTANCE_PROFILE 1`.

**Comment by mccarthyryanc** [comment]
Thanks @connormanning . That works, but I also had to add another environment variable for the region:
```bash
sudo docker run --env AWS_ALLOW_INSTANCE_PROFILE=1 --env AWS_DEFAULT_REGION=us-west-2 -it connormanning/entwine build -i s3://bucket/prefix/laz/ -o s3://bucket/prefix/ept/
```

Awesome library BTW! Really excited to test this out!
