### ISSUE TITLE
Error linking to LazPerf

### ISSUE THREAD

**Issue by addam** [connormanning/entwine#126]
I have a problem building Entwine on Ubuntu (GCC 7.2)

A clean `git clone` and `cmake` throws an error:
```
CMake Error at CMakeLists.txt:62 (find_package):
By not providing "FindLazPerf.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "LazPerf", but
CMake did not find one.

Could not find a package configuration file provided by "LazPerf" with any
of the following names:

  LazPerfConfig.cmake
  lazperf-config.cmake

Add the installation prefix of "LazPerf" to CMAKE_PREFIX_PATH or set
"LazPerf_DIR" to a directory containing one of the above files.  If
"LazPerf" provides a separate development package or SDK, be sure it has
been installed.
```

This is not _the_ error. I assume I am supposed to pull hobu/laz-perf and set LazPerf_DIR to `laz-perf/build/` (because it does contain `lazperf-config.cmake`). Configuration now runs well.

The build crashes only in the last moment, while linking executables:
```
[ 98%] Linking CXX executable entwine
../libentwine.so.2.0.0: undefined reference to `pdal::LazPerfDecompressor::LazPerfDecompressor(std::function<void (char*, unsigned long)>, std::vector<pdal::DimType, std::allocator<pdal::DimType> > const&, unsigned long)'
../libentwine.so.2.0.0: undefined reference to `pdal::LazPerfCompressor::LazPerfCompressor(std::function<void (char*, unsigned long)>, std::vector<pdal::DimType, std::allocator<pdal::DimType> > const&)'
collect2: error: ld returned 1 exit status
app/CMakeFiles/app.dir/build.make:201: recipe for target „app/entwine“ failed
make[2]: *** [app/entwine] Error 1
CMakeFiles/Makefile2:661: recipe for target „app/CMakeFiles/app.dir/all“ failed
make[1]: *** [app/CMakeFiles/app.dir/all] Error 2
make[1]: *** Waiting for unfinished tasks…
```

I use `libpdal 1.7.2-3` from the official ubuntu repository (release 18.10 cosmic). As a first step now, I'll try and build pdal from source.

**Comment by connormanning** [comment]
The laz-perf code in Entwine is not used anymore.  Can you `git pull` and try again - I've removed the no-longer-used references to it in the codebase with 2464fbea4e5cffb394457f5289c7c5f2a56355f4.

**Comment by addam** [comment]
Yes! This is solved.

Thank you very much! That was really a quick fix.

**Comment by rmam-spinworks** [comment]
I've experienced this very same problem while trying to build v1.3.0, which at this stage is the latest stable release of entwine.  Even if this issue is fixed in the development branch, it would be nice if this problem didn't emerged in a stable release.

**Comment by rmam-spinworks** [comment]
I believe I might have stumbled on what might be causing this problem.  See https://github.com/PDAL/PDAL/issues/2260
