### ISSUE TITLE
Exception in pool task: std::bad_alloc

### ISSUE THREAD

**Issue by mnphan65** [connormanning/entwine#130]
I run a docker / entwine command to build the indexing for an input URL point cloud file (Las 1.4), the file is  small, If I download the file and run pdalinfo, it reports every thing look right

>>  docker run -v /localdisk/data/pc/datasets:/localdisk/data/pc/datasets connormanning/entwine build -i http://ot-beta.sdsc.edu:8080/appLasSelectService1537469461222-1108335199/points.las -o /localdisk/data/pc/datasets/entwine/pc1537467636522

And I always got this error:
Scanning for new files...
1 / 1: http://ot-beta.sdsc.edu:8080/appLasSelectService1537469461222-1108335199/points.las
Exception in pool task: std::bad_alloc
Encountered an error: No point cloud files found
Exiting.

Can you help to point out what is wrong with this.
Thanks so much,
Minh

**Comment by connormanning** [comment]
It's because this is a LAS 1.4 file.  By default, when entwine scans your dataset, if the files are over HTTP it uses a range request just to get the header to extract bounds/points/SRS information.  This is not a very robust method but is extremely useful in many cases.  For LAS 1.4 though, some of this information might be at the end of the file, so when PDAL tries to get the information from the truncated file that Entwine created, it surpasses the size of the file looking for that information.

For now, you can work around this by adding the `-x` flag to either `entwine scan` or `entwine build`, which will force the full file to be downloaded during the scanning phase.

**Comment by mnphan65** [comment]
Thanks so much connormanning for quick help.
You said it is because las 1.4 issue, but I do have another las 1.4 data and I can run it without any issue ?

**Comment by mnphan65** [comment]
Also, when I added the -x flag, and rerun the command:

docker run -v /localdisk/data/pc/datasets:/localdisk/data/pc/datasets connormanning/entwine build -x -i http://ot-beta.sdsc.edu:8080/appLasSelectService1537469461222-1108335199/points.las -o /localdisk/data/pc/datasets/entwine/pc1537467636522

I still get the same error:

Scanning for new files...
1 / 1: http://ot-beta.sdsc.edu:8080/appLasSelectService1537469461222-1108335199/points.las
Exception in pool task: std::bad_alloc
Encountered an error: No point cloud files found
Exiting.

**Comment by connormanning** [comment]
Your command, with the `-x` flag, is working for me.  Can you try clearing your output directory at `/localdisk/data/pc/datasets/entwine/pc1537467636522` and re-running?  Some LAS 1.4 data could potentially work depending on the file size, and LAS 1.4 data should always work fine if it's local (i.e. not over HTTP/S3).

**Comment by vnandigam** [comment]
Thanks Conner. Looks like this was related to an older version of entwine that did not handle las 1.4 files properly. We have a separate issue related to the lastest version of entwine docker image on centos7 and las 1.4 files (unrelated to this issue).

**Comment by AlbionS** [comment]
I have the same error :
sudo docker run -it -v /home/ubuntu/Desktop/:/entwine connormanning/entwine:2.1 build
-x -i /entwine/ch/ch00029.las -o /entwine/etp_00008/ --tmp /entwine/temp/ --threads 4
Scanning input
1/1: /entwine/ch/ch00029.las
Exception in pool task: During /entwine/ch/ch00029.las: std::bad_alloc
SRS could not be determined
Encountered an error: No points found!
Exiting.

Though my file is local !! I dont know why some of the las files are not working ? 
@vnandigam  @mnphan65
