### ISSUE TITLE
CMakeLists depends on PDAL 1.2.0 but source code depends on higher version

### ISSUE THREAD

**Issue by rmam-spinworks** [connormanning/entwine#140]
The project's CMakeLists suggests that Entwine depends on PDAL 1.2.0 (check CMakeLists.txt:69) but the project's source code includes headers that were only added to PDAL after the release of v1.4.0.

**Comment by rmam-spinworks** [comment]
Nice.  Keep up the good work.

**Comment by connormanning** [comment]
This has been addressed [here](https://github.com/connormanning/entwine/blob/master/CMakeLists.txt#L69) - the upcoming Entwine 2.0 release will depend on PDAL >= 1.8.0.

**Comment by rmam-spinworks** [comment]
Just a FYI, in Entwine v2.0.0 the project's CMakeLists still includes a reference to PDAL v1.2:

```
set(PDAL_FIND_VERSION 1.2)
find_package(PDAL ${PDAL_FIND_VERSION} REQUIRED CONFIG NO_POLICY_SCOPE)
```

**Comment by connormanning** [comment]
Can you post a github link to this line?  Cannot find it - I'm seeing 1.8 in both [Entwine 2.0](https://github.com/connormanning/entwine/blob/2.0.0-maintenance/CMakeLists.txt#L69) and in the updated build tooling in [Entwine master](https://github.com/connormanning/entwine/blob/master/cmake/pdal.cmake#L1)

**Comment by rmam-spinworks** [comment]
I've just checked my local repo and I've noticed that my v2.0 branch was not pointing to where it should.  My bad. 

Sorry for all the trouble and keep up the good work.
