### ISSUE TITLE
CMakeLists.txt sets entwine version to v1.1.0 in branch v1.3.0

### ISSUE THREAD

**Issue by rmam-spinworks** [connormanning/entwine#141]
Title is pretty much self-contained.  The [CMakeLists.txt of entwine v1.3.0](https://github.com/connormanning/entwine/blob/1.3.0/CMakeLists.txt) sets entwine's version as 1.1.0.

**Comment by connormanning** [comment]
Fixed on the 1.3.0-maintenance branch.
