### ISSUE TITLE
Cannot convert EPT to Cesium as convert function is looking in the wrong location for hierarchy

### ISSUE THREAD

**Issue by GeoBrit** [connormanning/entwine#143]
Hi, I am running the following command:

`sudo docker run -it -v $HOME:$HOME connormanning/entwine convert -i /home/ec2-user/entwine/hedemo -o /home/ec2-user/entwine/cesium/hedemo -t 10`

and i get the following error:

`Converting:
        Input:  /home/ec2-user/entwine/hedemo/
        Output: /home/ec2-user/entwine/cesium/hedemo/
        Color:  intensity
        Truncate: no
        Threads: 6
        Root geometric error: 887.188
Running...
Encountered an error: Could not read file /home/ec2-user/entwine/hedemo/h/0-0-0-0.json
Exiting.
`
However, the file it is looking for is available in "ept-hierarchy" folder, the "h" folder does not exist.

Regards,
Steve

**Comment by connormanning** [comment]
This was probably broken last night due to this change: https://github.com/connormanning/entwine/pull/139

I'll take a look.
