### ISSUE TITLE
Entwine Convert does not bring across components

### ISSUE THREAD

**Issue by GeoBrit** [connormanning/entwine#144]
Hi,

I am running the "convert" tool on entwine to build the cesium tileset, however, it only brings over the X,Y,Z components (and creates the non-existent RGB components).  Intensity, classification, number of returns etc do not exist in the generated tileset.  For me, classification is the most important, but i am sure, people will think the other components are important.

I have studied the documentation, and i cannot find anything.  The components are available in the EPT data that is created.

Thanks,
Steve

**Comment by connormanning** [comment]
With the entwine convert tool, you can select a coloring from a limited set of `colorType` values which are described [here](https://github.com/connormanning/entwine/blob/master/doc/configuration.md#colorType).  It looks like what you're really looking for is 3D Tiles [batch table](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/TileFormats/BatchTable/README.md) functionality.  Entwine 1.3 has this functionality, but the current software on `master` does not.

This is related to #118 which you can read through for some more context.  There is a 3rd-party entwine->3D Tiles converter called [Entium](https://github.com/commaai/entium), but in preparation for Entwine's 2.0 release there have recently been some changes that make Entium slightly out of date.  I've opened an issue for that [here](https://github.com/commaai/entium/issues/1).

**Comment by GeoBrit** [comment]
Hi Connor, thanks for your prompt reply.
Is there a docker image of a nightly build of the 1.3 release which would contain the required components when converting?

I think you are correct in understanding what i am after, you can find it here - here it the demo example of exactly what i need: [https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=3D%20Tiles%20Point%20Cloud%20Classification.html&label=All](url)

I did try entium earlier, but bizarrely, ran into the same issue i raised about with you last week which you promptly fixed [https://github.com/connormanning/entwine/issues/143](url)

**Comment by connormanning** [comment]
This is being addressed via 1.3.0-maintenance in #150.
