### ISSUE TITLE
Entwine 2.0rc1 cannot find any point

### ISSUE THREAD

**Issue by leonardokidd** [connormanning/entwine#147]
After I buit entwine 2.0 with PDAL 1.8, entwine cannot find any points. When I run entwine_test, all of them throw "No points found!" error.

Here is the entwine_test output.

[==========] Running 29 tests from 5 test cases.
[----------] Global test environment set-up.
[----------] 7 tests from srs
[ RUN      ] srs.empty
[       OK ] srs.empty (0 ms)
[ RUN      ] srs.emptyString
[       OK ] srs.emptyString (0 ms)
[ RUN      ] srs.fromHorizontalCode
[       OK ] srs.fromHorizontalCode (2 ms)
[ RUN      ] srs.fromCompoundCode
[       OK ] srs.fromCompoundCode (0 ms)
[ RUN      ] srs.fromHorizontalWkt
[       OK ] srs.fromHorizontalWkt (0 ms)
[ RUN      ] srs.fromCompoundWkt
[       OK ] srs.fromCompoundWkt (1 ms)
[ RUN      ] srs.fromJson
[       OK ] srs.fromJson (0 ms)
[----------] 7 tests from srs (3 ms total)

[----------] 3 tests from version
[ RUN      ] version.basic
[       OK ] version.basic (0 ms)
[ RUN      ] version.string
[       OK ] version.string (0 ms)
[ RUN      ] version.comparison
[       OK ] version.comparison (0 ms)
[----------] 3 tests from version (0 ms total)

[----------] 9 tests from scan
[ RUN      ] scan.nonexistentDirectory
[       OK ] scan.nonexistentDirectory (3 ms)
[ RUN      ] scan.nonexistentFile
[       OK ] scan.nonexistentFile (6 ms)
[ RUN      ] scan.single
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] scan.single (5 ms)
[ RUN      ] scan.deepScan
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] scan.deepScan (4 ms)
[ RUN      ] scan.multi
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] scan.multi (19 ms)
[ RUN      ] scan.reprojection
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] scan.reprojection (5 ms)
[ RUN      ] scan.deepScanReprojection
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] scan.deepScanReprojection (5 ms)
[ RUN      ] scan.reprojectionHammer
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] scan.reprojectionHammer (4 ms)
[ RUN      ] scan.outputFile
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] scan.outputFile (5 ms)
[----------] 9 tests from scan (56 ms total)

[----------] 7 tests from build
[ RUN      ] build.basic
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] build.basic (16 ms)
[ RUN      ] build.continued
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] build.continued (17 ms)
[ RUN      ] build.fromScan
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] build.fromScan (16 ms)
[ RUN      ] build.subset
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] build.subset (16 ms)
[ RUN      ] build.invalidSubset
[       OK ] build.invalidSubset (98 ms)
[ RUN      ] build.subsetFromScan
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] build.subsetFromScan (16 ms)
[ RUN      ] build.reprojected
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] build.reprojected (19 ms)
[----------] 7 tests from build (198 ms total)

[----------] 3 tests from read
[ RUN      ] read.count
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] read.count (5 ms)
[ RUN      ] read.data
unknown file: Failure
C++ exception with description "No points found!" thrown in the test body.
[  FAILED  ] read.data (4 ms)
[ RUN      ] read.filter
[       OK ] read.filter (0 ms)
[----------] 3 tests from read (9 ms total)

[----------] Global test environment tear-down
[==========] 29 tests from 5 test cases ran. (266 ms total)
[  PASSED  ] 14 tests.
[  FAILED  ] 15 tests, listed below:
[  FAILED  ] scan.single
[  FAILED  ] scan.deepScan
[  FAILED  ] scan.multi
[  FAILED  ] scan.reprojection
[  FAILED  ] scan.deepScanReprojection
[  FAILED  ] scan.reprojectionHammer
[  FAILED  ] scan.outputFile
[  FAILED  ] build.basic
[  FAILED  ] build.continued
[  FAILED  ] build.fromScan
[  FAILED  ] build.subset
[  FAILED  ] build.subsetFromScan
[  FAILED  ] build.reprojected
[  FAILED  ] read.count
[  FAILED  ] read.data

Here is the output when I try to run build:
$ ./entwine build -i PointClouds/output.laz -o entwine_data/result2/ -r EPSG:4978
Scanning input
1 / 1: PointClouds/output.pcd
Exception in pool task: in Json::Value::resolveReference(key, end): requires objectValue
Encountered an error: No points found!
Exiting.

Thanks in advance.

**Comment by hobu** [comment]
did you figure it out?

**Comment by leonardokidd** [comment]
No, but I saw the build failed report. I assumed this is a known issue.
