### ISSUE TITLE
Ubuntu Build Instructions

### ISSUE THREAD

**Issue by pogilon** [connormanning/entwine#148]
Hi,

I am having a bit of troubles trying to compile Entwine natively on Ubuntu, given that I could not find a clear description anywhere about the necessary dependencies. Could you please give me a hand with this? Thanks.

**Comment by hobu** [comment]
The dependencies can be reviewed by searching for the find_package method calls in the CMakeLists.txt file. See https://github.com/connormanning/entwine/blob/master/CMakeLists.txt for more detail.

**Comment by pogilon** [comment]
Thank you @hobu. That is clear. I think my problem is relative to PDAL. I think the CMakeLists.txt may not be accurate about the PDAL version and the PDA built (which dependencies).
