### ISSUE TITLE
temporal bounds

### ISSUE THREAD

**Issue by adamsteer** [connormanning/entwine#149]
Adding temporal bounds of a dataset to EPT metadata might be useful:
```
{
    "bounds": [634962.0, 848881.0, -1818.0, 639620.0, 853539.0, 2840.0],
    "boundsConforming": [635577.0, 848882.0, 406.0, 639004.0, 853538.0, 616.0],
     \\ new element here
    "temporalBounds": [2018-11-23T00:00:30.75, 2018-11-23T00:02:30.75],
    "dataType": "laszip",
    "hierarchyType": "json",
    "points": 10653336,
    "schema": [
    ...
    ],
    "srs": {
    ...
    },
    "ticks" : 256,
    "version" : "1.0.0”
}
```

**Comment by connormanning** [comment]
The meaning here is `[minGpsTime, maxGpsTime]`, correct?  For large sets (countries, states, etc) whose acquisition spans many months or multiple years, how might this field be used?

**Comment by adamsteer** [comment]
yes, exactly.

The idea comes from treating 'surveys' as logical units of data, and the case of a spatiotemporal metadata query without having to look at the actual data - for example 'do I have data from a place at a time?' (which may actually still be a pretty broad time window)

I hadn't considered merging data over time - and sure, a range limit on `GpsTime` will do the same in a huge merged dataset, but take longer. 

Maybe it's a field for a metadata layer above the EPT asset (say, a per-survey catalogue made for datasets pre-entwine-ifying).

**Comment by hobu** [comment]
I think `time` is out of scope for EPT, or alternative, indexing every other dimension to support range queries is *in scope* for EPT. A special bolt-on seems destined to fail. Users can control their own secondary indexing independent of EPT with finer control.

**Comment by connormanning** [comment]
I tend to agree.  I think EPT already has sufficient support for this use-case without adding a new required key.  Because EPT is a spatial index I think it makes sense for `bounds` information to be required - but time information seems secondary.

One method is that an application do exactly as you laid out with `temporalBounds` and still be valid EPT, extended for a single application, without it being required for *all* EPT resources.

A better method in my opinion would be for the application to put this information in the `ept-sources` per-file `metadata`.  Then it could be aggregated by a client for a resource-wide range while still being relevant file-level metadata.

**Comment by connormanning** [comment]
This makes me think about EPT "extensions" more generally.  By this, I mean well-defined application-level additions to EPT that may be out of scope for EPT itself (for minimizing the implementation footprint, specialized functionality, etc), while remaining compliant with vanilla EPT.  This would include anything that added extra keys into EPT's JSON metadata or even new files without changing anything reserved for EPT itself.

This would fall into that category.  Others I've considered:
- hexbin-like boundary information within the EPT data files
- adding LAZ files of even coarser resolution than the `0-0-0-0` node for rendering many EPT datasets at once over a very wide area
- dimension histograms

It would be nice if there was a place for people to define extensions like this, perhaps with the support of Entwine itself for some of them (`entwine build ... --extend temporalBounds` for example).

Something to consider for the roadmap.  However I'm going to close this ticket as I think temporal bounds is a bit beyond the scope of EPT itself.
