### ISSUE TITLE
Unable to process pointcloud "No type found for undefined dimension"

### ISSUE THREAD

**Issue by Hisol** [connormanning/entwine#158]
I am attempting to re-index pointclouds that have previously been indexed with (docker based) Entwine 1.x.  I am using the same source LAS files for the indexing however, with the newer version of Entwine each LAS file seems to generate the following:

(readers.las Error) Global encoding WKT flag not set for point format 6 - 10.
Exception in pool task: No type found for undefined dimension.
SRS could not be determined

And the scan ends stating that SRS could not be determined and with very bare output, if I attempt a build using the scan output, as well as the warnings for each LAS file I get an error at the end stating that no points were found.

I have run the exact same LAS file though 1.3 and it still complains about point formats but completes 

(readers.las Error) Invalid SRS specification.  GeoTiff not allowed with point formats 6 - 10.
Writing details to /tmp/out.entwine-inference...
<snip>

I am invoking with:
docker run -it -v `pwd`:/tmp connormanning/entwine:1.3 infer -i /tmp/Pontshill_2_000015.las -o /tmp/out

and
docker run -it -v `pwd`:/tmp connormanning/entwine:latest scan -i /tmp/Pontshill_2_000015.las -o /tmp/out2

I have tried forcing an SRS via a config file:
{
"reprojection": {
        "in": "EPSG:27700",
        "out": "EPSG:27700",
        "hammer": true
},
"input": "/tmp/Pontshill_2_000015.las",
"output": "/tmp/scanout"
}

which gives the No points found! error:

docker run -it -v `pwd`:/tmp connormanning/entwine:latest scan -c /tmp/scan.config
Scanning:
	Input: /tmp/Pontshill_2_000015.las
	Threads: 8
	Reprojection: EPSG:27700 (OVERRIDING file headers) -> EPSG:27700
	Trust file headers? yes

1 / 1: /tmp/Pontshill_2_000015.las
(readers.las Error) Global encoding WKT flag not set for point format 6 - 10.
(readers.las Error) Global encoding WKT flag not set for point format 6 - 10.
Exception in pool task: No type found for undefined dimension.
Encountered an error: No points found!
Exiting.

Is there something I am missing?

**Comment by connormanning** [comment]
Sounds like it could be a bug, but I think I'd need the file in order to fix it.  If you could attach the file or email it to me, I can take a look.

**Comment by connormanning** [comment]
Thanks for providing the file.  It seems that the issue is your dimension named `Pulse width`, which is not a valid dimension name according to PDAL since it contains a space (see dimension name validation code [here](https://github.com/PDAL/PDAL/blob/master/pdal/DimUtil.hpp#L173-L187)).

For example, if I do `pdal translate <your-file>.las translated.las`(note the lack of forwarding extra-dimensions which effectively strips this dimension), `translated.las` is indexable via Entwine.

**Comment by Hisol** [comment]
Did my email reach you? I know in past sometimes my emails seem to have gotten lost?

**Comment by Hisol** [comment]
Thanks for the update, is there any way that Entwine could strip this itself (as the earlier version seemed to do), or am I going to need to add an additional processing step before Entwine?

**Comment by Hisol** [comment]
As a quick and dirty test I edited the LAS file and changed the space in "Pulse width" to an "x" removing the space.  The behaviour of Entwine is unchanged.  Could it be this or another dimension in the file is not recognised and causing the issue, rather than simply the name not matching the standard?

As I have mentioned the older version of Entwine indexes this file (with some warnings) but successfully.

**Comment by connormanning** [comment]
This appears to be an issue with Entwine's usage of the PDAL API with non-standard dimensions (e.g. whose name doesn't appear [here](https://pdal.io/dimensions.html)).  I'm looking into how to fix it properly.  For now, if you're alright with stripping the pulse-width dimension from your Entwine output, you can get around this by using a `config.json` with contents:
```
{ "schema": [
    { "name": "X", "size": 4, "type": "signed" },
    { "name": "Y", "size": 4, "type": "signed" },
    { "name": "Z", "size": 4, "type": "signed" },
    { "name": "Intensity", "size": 2, "type": "unsigned" },
    { "name": "ReturnNumber", "size": 1, "type": "unsigned" },
    { "name": "NumberOfReturns", "size": 1, "type": "unsigned" },
    { "name": "ScanDirectionFlag", "size": 1, "type": "unsigned" },
    { "name": "EdgeOfFlightLine", "size": 1, "type": "unsigned" },
    { "name": "Classification", "size": 1, "type": "unsigned" },
    { "name": "ScanAngleRank", "size": 4, "type": "float" },
    { "name": "UserData", "size": 1, "type": "unsigned" },
    { "name": "PointSourceId", "size": 2, "type": "unsigned" },
    { "name": "GpsTime", "size": 8, "type": "float" },
    { "name": "Red", "size": 2, "type": "unsigned" },
    { "name": "Green", "size": 2, "type": "unsigned" },
    { "name": "Blue", "size": 2, "type": "unsigned" }
] }
```

And running Entwine with:
```
entwine build -c config.json <your other args>
```

**Comment by Hisol** [comment]
Stripping out the pulse width isn't an issue.  Do you mean to run the LAS files through pdal initially to strip out the additional dimensions? or should specifying that schema cause Entwine to ignore all dimensions not specified?

I have tried adding that schema to my Entwine build config with the sample file I sent to you and get the same "No Points found!" error.

My full config:

{
"reprojection": {
	"in": "EPSG:27700",
	"out": "EPSG:27700",
	"hammer": true
},
"schema": [
    { "name": "X", "size": 4, "type": "signed" },
    { "name": "Y", "size": 4, "type": "signed" },
    { "name": "Z", "size": 4, "type": "signed" },
    { "name": "Intensity", "size": 2, "type": "unsigned" },
    { "name": "ReturnNumber", "size": 1, "type": "unsigned" },
    { "name": "NumberOfReturns", "size": 1, "type": "unsigned" },
    { "name": "ScanDirectionFlag", "size": 1, "type": "unsigned" },
    { "name": "EdgeOfFlightLine", "size": 1, "type": "unsigned" },
    { "name": "Classification", "size": 1, "type": "unsigned" },
    { "name": "ScanAngleRank", "size": 4, "type": "float" },
    { "name": "UserData", "size": 1, "type": "unsigned" },
    { "name": "PointSourceId", "size": 2, "type": "unsigned" },
    { "name": "GpsTime", "size": 8, "type": "float" },
    { "name": "Red", "size": 2, "type": "unsigned" },
    { "name": "Green", "size": 2, "type": "unsigned" },
    { "name": "Blue", "size": 2, "type": "unsigned" }
],
"bounds": [0, 0, -3000, 1300000, 1300000, 3000],
"input": "/tmp/Pontshill_2_000015.las",
"output": "/tmp/buildouti2"
}

and calling with:

docker run -it -v `pwd`:/tmp connormanning/entwine build -c /tmp/build2.config

Thanks for your help with this.

**Comment by connormanning** [comment]
Can you try again with the changes from 115f81b?  With the normal workflow from the original issue - no config file required.  Looks like you're using docker - I've just pushed the `connormanning/entwine:latest` image with that change.

**Comment by Hisol** [comment]
That's looking MUCH happier :)

Index completed in 1 seconds.
Save complete.
	Points inserted: 42,868

Many thanks for the speedy fix
