### ISSUE TITLE
Failure when too much threads

### ISSUE THREAD

**Issue by smercier** [connormanning/entwine#16]
Hi,  I set threads option too hight when I tried to process large volume of Pointcloud files. entwine failed before the end of the process.  No error message, and number of files processed was not the same each time.  After lowered threads, I succeed to process all files (545).

**Comment by connormanning** [comment]
This is almost certainly an OOM-killed process from running out of memory.  The messages you normally see in this situation unfortunately don't appear in Docker the way it's currently built.  If running natively, you'd see a message in `/var/log/syslog`.

You could try enabling swap, which will slow down processing time if used, but will allow your builds to finish.  It would also let you track how much memory Entwine is using for your thread count setting so you can decide on a good value.  How many threads were you trying?  How much RAM is available to your VM?

**Comment by smercier** [comment]
Initial config file was a bit agressive with 12 threads!   The VM Server have 4 CPU so I've lowered to 6 threads to make it work (entwine didn't use swap).  Server have 16GB of RAM with 4GB of swap.  Since docker use LXC I presumed MEM and Swap are both used by entwine container?   

tks
