### ISSUE TITLE
entwine: symbol lookup error: entwine: undefined symbol: _ZN4Json5ValueC1ERKSs (on Ubuntu)

### ISSUE THREAD

**Issue by m0b0u0** [connormanning/entwine#163]
Installed `entwine 2.0.0` on Ubuntu 18.04.1 LTS using `conda` as described in [Quickstart](https://entwine.io/quickstart.html). Installation is fine.

However when I run this example `entwine build -i https://entwine.io/data/red-rocks.laz -o entwine/red-rocks`, it's failing with the following error: `entwine: symbol lookup error: entwine: undefined symbol: _ZN4Json5ValueC1ERKSs`.

I installed the same way on a Mac and rand the same example without any problem. Just seeing the issue on Ubuntu.

**Comment by hobu** [comment]
I think entwine Conda needs to be rerendered.

**Comment by conorbros** [comment]
I am seeing this issue aswell. What was the solution?
