### ISSUE TITLE
tileset.json output broken

### ISSUE THREAD

**Issue by tomvantilburg** [connormanning/entwine#164]
Did a fresh pull today but found out that the tileset.json output for cesium tiles has the following layout:

```
{
  "asset": [
    "version",
    "0.0"
  ],
  "geometricError": 33.5625,
  "root": {
    "boundingVolume": [
      "box",
      [
        3887781.0,
        333981.0,
        5028383.0,
        1074.0,
        0,
        0,
        0,
        1074.0,
        0,
        0,
        0,
        1074.0
      ]
    ],...

```
I get the feeling this has something today with this commit, but with my limited c++ can't say for sure: https://github.com/connormanning/entwine/commit/3339745ec3a2d55313d5fde00fce31083d83a39e#diff-a8baf6b2885b2b7cb32a4decf6fbd291

(these curly brackets easily get messy ;-)

**Comment by connormanning** [comment]
Good catch.  This should be fixed now, and docker containers are updated.
