### ISSUE TITLE
Append attributes?

### ISSUE THREAD

**Issue by mccarthyryanc** [connormanning/entwine#166]
Is there a native way to append attributes to an entwine dataset? It looks like this is still possible through Greyhound, but the [docs](https://greyhound.io/clientDevelopment.html#command-set) don't seem to advertise this anymore. Maybe this is something more appropriate for a PDAL pipeline?

**Comment by connormanning** [comment]
This functionality is in progress via PDAL - there is currently an implementation on the [ept-writer](https://github.com/PDAL/PDAL/tree/ept-writer) branch.  I'm currently writing some docs for it and need to add some unit tests, and then I'll be making a PR to `master` this week.  The API will look something like this, pending PR discussion:

Write an appended dimension, mapping a modified `Classification` value to a local path:
```
[{
    "type": "readers.ept",
    "filename": "http://na.entwine.io/autzen/ept.json"
}, {
    "type": "filters.assign",
    "assignment": "Classification[:]=0"
}, { 
    "type": "filters.smrf" 
}, {
    "type": "writers.ept",
    "addons": { "~/entwine/addons/autzen/smrf": "Classification" }
}]
```

Read with appended dimension, mapping this addon dimension back to `Classification`:
```
[{
    "type": "readers.ept",
    "filename": "http://na.entwine.io/autzen/ept.json",
    "addons": { "Classification": "~/entwine/addons/autzen/smrf" }
}, {
    "type": "writers.las",
    "filename": "autzen-ept-smrf.laz"
}]
```

**Comment by mccarthyryanc** [comment]
Whoa, Awesome! I'll keep my eyes on that branch and PR.

**Comment by connormanning** [comment]
PR submitted: PDAL/PDAL#2391

**Comment by mccarthyryanc** [comment]
@connormanning, looking over the PR, PDAL will only be able to write to an ept addon dataset. Is the plan to add this to the EPT spec? Or, will there be a way to reference the addon dataset from the main ept.json file?
