### ISSUE TITLE
Numpy and JavaScript compatible EPT content-encoding

### ISSUE THREAD

**Issue by hobu** [connormanning/entwine#173]
EPT storage could be made conveniently Numpy- and JavaScript- compatible with a few simple modifications:

* Allow storage alternative compression such as [Zstd](https://github.com/facebook/zstd) that is compatible with the [numcodecs](https://numcodecs.readthedocs.io/en/stable/zstd.html) package.
* Emit a an optional [dtype](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html) object in the `schema`
* Develop a Python library based on [Zarr](https://zarr.readthedocs.io/en/stable/#) that abstracts EPT similar to Potee or [readers.ept](https://pdal.io/stages/readers.ept.html)

**Comment by connormanning** [comment]
Going to close this until there's a specific type with a concrete use-case to add support for.  Zstandard compression support has been added to Entwine as a Javascript/Python-capable generic compression format.
