### ISSUE TITLE
Profile in black

### ISSUE THREAD

**Issue by Raquel0** [connormanning/entwine#174]
Hi! :raising_hand:
First of all, congrats to the whole crew that make this possible, i'm hugely thankful.
As it happened to me with potree v1.6, after building EPT, everything seems to work perfectly but profile extraction tool. It looks like points into profile window are black, like background color, and it doesn't show profile properly. Does anybody know how can i solve this?
Thank you very much! :smile:

**Comment by connormanning** [comment]
I think this is an issue in the current Potree library itself rather than being related to EPT - I've just opened an issue there at potree/potree#629.
