### ISSUE TITLE
Conda based Entwine install fails to run (dependencies)

### ISSUE THREAD

**Issue by tomkom** [connormanning/entwine#175]
Hi,
Running on OSX - Mojave, I have followed the entwine tutorial to install Entwine.

Failing to run Entiwne due to dependencies ( fonts?):
 

$entwine --version
dyld: Library not loaded: @rpath/libfontconfig.1.dylib
  Referenced from: /Users/tomkom/anaconda3/lib/libpoppler.78.dylib
  Reason: Incompatible library version: libpoppler.78.dylib requires version 14.0.0 or later, but libfontconfig.1.dylib provides version 13.0.0
Abort trap: 6

I assume this is a dependency from gdal, installed as conda install gdal.

**Comment by adamsteer** [comment]
it’s a bit deeper as far as I can see -  using:

`conda create -n newenv pdal entwine -c conda-forge`

…I get:

```
pdal -h
dyld: Library not loaded: @rpath/libgif.7.dylib
  Referenced from: /Users/adam/anaconda3/envs/entwinetest/lib/libgdal.20.dylib
  Reason: image not found
Abort trap: 6

entwine -h
dyld: Library not loaded: @rpath/libgif.7.dylib
  Referenced from: /Users/adam/anaconda3/envs/entwinetest/lib/libgdal.20.dylib
  Reason: image not found
Abort trap: 6
```

…with `gdalinfo` reporting the same error.

...from the laundry list of dependencies, relevant things seem to be:

```
entwine            conda-forge/osx-64::entwine-2.0.0-h9f9578c_2
...
gdal               conda-forge/osx-64::gdal-2.4.0-py37h0e3174d_1002
...
libgdal            conda-forge/osx-64::libgdal-2.4.0-h89caebc_1002
…
 pdal               conda-forge/osx-64::pdal-1.8.0-py37h24fc07d_8
…
 python             conda-forge/osx-64::python-3.7.1-h145921a_1000
```

I tinkered around removing GDAL and using different versions. 2.4.1 or 2.3.2 get pdal to work but not entwine. entwine wants to remove both and use 2.4.0.

hmm. immediate workaround is `docker run entwine` - but that’s less convenient for the long term.

**Comment by tomkom** [comment]
Thanks,  I started with exactly the same error,  thought this is a messed
gdal install,  and after presumably fixing that,  ended up with the font
dependency hell.

:(
Will try docker.
M.

**Comment by hobu** [comment]
Entwine needs to be rerendered. There has been significant churn in the conda forge recipes due to OpenSLL migration.  Track https://github.com/conda-forge/entwine-feedstock/pull/5 for details.

**Comment by hobu** [comment]
Refreshed. Please reopen if you still have issues.

**Comment by adamsteer** [comment]
fantastic - tested and working as per my recipe above. Thanks Howard
