### ISSUE TITLE
Upgrade Cesium tileset.json to version 1.0

### ISSUE THREAD

**Issue by GeoSpark** [connormanning/entwine#177]
Entwine currently exports version 0.0  Cesium tilesets which have been superseded for some time. Validating an Entwine-generated file against the latest spec highlights that "url" needs to be changed to "uri", and of course the version number needs to be bumped to 1.0

**Comment by connormanning** [comment]
Are these the only changes required?

**Comment by GeoSpark** [comment]
As far as I can tell. I ran a modest Entwine-generated tileset.json through
a validator and it came up clean once I changed url to uri. I also tried it
with my large tileset.json with the same result. The only thing I haven't
tried is nested tileset files, but that part of the spec hasn't changed as
far as I know.

Bounding box and content semantics haven't changed, and that's pretty much
all Entwine generates at this stage.
