### ISSUE TITLE
POSIX stat failed

### ISSUE THREAD

**Issue by xyz-mtl** [connormanning/entwine#179]
Hi,

I have an issue when i run this command:
```
docker run -it -v ~/entwine:/entwine connormanning/entwine build -i ** -o /entwine/red-rocks
Scanning input
Resolving [file]: ** ...Encountered an error: Error globbing - POSIX stat failed
Exiting.
```

**Comment by connormanning** [comment]
This is an issue with your Docker volume mapping.  I recommend you use the Conda distribution for access to your filesystem natively or to read the documentation about Docker's volume mapping.
