### ISSUE TITLE
 Entwine master (9f6d9cc) doesn't compiles with PDAL after the nlohmann json changes

### ISSUE THREAD

**Issue by sunapi386** [connormanning/entwine#181]
- Entwine `9f6d9cc` can compile with PDAL `58c77bc4`. But...
- Newer PDAL commits has nlohmann issues.
- Older PDAL commits have ZSTD issues.

Entwine has PDAL as dependency so it need to catch up to PDAL's master branch. Similar to #84, I suppose.

**Comment by connormanning** [comment]
The PDAL pin for Entwine right now is `1.9-maintenance`, pending resolution of PDAL/PDAL#2491.

**Comment by connormanning** [comment]
Entwine `master` should now build against both PDAL `master` and `1.9.1`.
