### ISSUE TITLE
Docker connormanning/entwine issue with Arbiter config/credentials on AWS

### ISSUE THREAD

**Issue by paul-thompson-helix** [connormanning/entwine#185]
This issue relates to docker image  `connormanning/entwine`       latest              `e6d2caf74b1e` - from which I am using the PDAL EPT reader.

I'm getting a persistent error relating to the AWS S3 authorization:
`<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'ap-southeast-2'</Message><Region>ap-southeast-2</Region><RequestId>xxx</RequestId><HostId>xxx/xxx/xxx=</HostId></Error>`

In the past it has been sufficient to set environment AWS_DEFAULT_REGION and/or use 

https://entwine.io/configuration.html#arbiter

Tried setting all the usual AWS environment variables as well as reviewing the source of PDAL EPT reader & Arbiter for config options.

This issue did not affect earlier builds of `connormanning/entwine`

**Comment by paul-thompson-helix** [comment]
I found that that `pdal/pdal:1.9`  `1109b0c6f09c` does not have this issue.

It might be an issue on `pdal/master:latest`

**Comment by connormanning** [comment]
Thanks for the submission - I will look into this over the next few days.
