### ISSUE TITLE
Demos at http://cesium.entwine.io have floating points

### ISSUE THREAD

**Issue by Nogbit** [connormanning/entwine#189]
The linked (http://cesium.entwine.io/) demos from this repo (built with this repo?) all have the lidar floating about 50 feet the imagery, something isn't quite right.  Chrome 74, Mac.  The Potree demos have everything aligned correctly though.

Cesium
![image](https://user-images.githubusercontent.com/5131608/58754333-97dd7a00-8482-11e9-9a61-e94102d2c8fc.png)

Potree
![image](https://user-images.githubusercontent.com/5131608/58754343-bb082980-8482-11e9-9ec3-5483609ee1b2.png)

**Comment by Nogbit** [comment]
Better images..

Cesium
![image](https://user-images.githubusercontent.com/5131608/58754356-0e7a7780-8483-11e9-8c04-d88effff1283.png)

Potree
![image](https://user-images.githubusercontent.com/5131608/58754359-28b45580-8483-11e9-9b23-5bd94da0ecfa.png)

**Comment by connormanning** [comment]
I don't think that this is an Entwine issue - Cesium's own demos of identical datasets seem to show the same behavior.

For example, here is a screenshot of Entwine's St. Helens data in Cesium (see it [here](http://cesium.entwine.io/?url=http://cesium.entwine.io/data/st-helens/tileset.json)):
![Entwine Mt St Helens](https://user-images.githubusercontent.com/5015470/61662922-0e357600-ac95-11e9-953e-a130bb456429.png)

And here is a similar angle from Cesium's own Sandcastle example of the same dataset (see it [here](https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D%20Tiles%20Point%20Cloud%20Shading.html), where the only change I made for this screenshot is to shrink the point size to 3):
![Cesium Mt St Helens](https://user-images.githubusercontent.com/5015470/61663022-49d04000-ac95-11e9-8ab4-d5408060730e.png)

I've also just tried tiling the Red Rocks data from your screenshots with Cesium's own service, which produced the same elevation offset as your screenshots:
![Cesium Red Rocks](https://user-images.githubusercontent.com/5015470/61663669-bf88db80-ac96-11e9-92bb-ea46fbc993ab.png)

So I would think that this has to do with the terrain model and not the point cloud.
