### ISSUE TITLE
Cesium 3D tiles performance issues

### ISSUE THREAD

**Issue by ThornM9** [connormanning/entwine#198]
Referencing an issue I filed on the Cesium Github repo.
[https://github.com/AnalyticalGraphicsInc/cesium/issues/7932](url)

Essentially, point cloud tilesets that have been tiled with Entwine have performance issues on newer versions of Cesium. This issue does not exist in tilesets tiled with Cesium Ion. The details of the case can be found in the above referenced issue.

**Comment by connormanning** [comment]
OBE since Entwine no longer directly generates 3D Tiles - perhaps the underlying reason is still an issue with viewer.copc.io (which performs a similar translation in the browser) but that would be inapplicable to this repo so I'll close this one.
