### ISSUE TITLE
'scan' with unicode characters does not always find files

### ISSUE THREAD

**Issue by hobu** [connormanning/entwine#199]
A scan of a directory with the file called `汉字.laz` in it will fail to glob the laz file. A direct scan of `entwine scan 汉字.laz` succeeds, however.

**Comment by connormanning** [comment]
This works properly for me on OS X, if necessary we can reopen with additional info.

**Comment by hobu** [comment]
I thought we fixed this in PDAL about two years ago. It was a bit invasive to the Utils methods
