### ISSUE TITLE
Pix4D Point Clouds

### ISSUE THREAD

**Issue by landpoint** [connormanning/entwine#20]
Hello - We have had issues with Pix4D (latest version) point clouds displaying only in white, with RGB selected. If we take the point clouds out of Pix4D and runthem into another program, such as Leica Cyclone, and then through Entwine, we are able to see point colors natively. Any input is appreciated. Thanks!

**Comment by connormanning** [comment]
Can you point me toward a sample file that produces this behavior when indexed? I can take a look.

**Comment by landpoint** [comment]
Here's a link to the .las file: https://www.dropbox.com/s/vvl5fmyszvch4ch/sec_5_master_group1_densified_point_cloud.las?dl=0

Also, just noticed that it displays the colors appropriately in plas.io but not in potree.

**Comment by hobu** [comment]
```
  Minimum Color (RGB):	3072 1024 0
  Maximum Color (RGB):	65280 65280 65280
```

Looks like 16bit color.

**Comment by landpoint** [comment]
Forgive my ignorance on this, but where should I start looking to make adjustments for this to work properly? Right now we have little control over the .las file generated directly from Pix4D.

**Comment by hobu** [comment]
You should be able to use pdal or lastools to scale it to 8bit color.

**Comment by landpoint** [comment]
Got it - las2las with the option scale_rgb_down worked. Thanks for the help
