### ISSUE TITLE
Release Entwine 2.1

### ISSUE THREAD

**Issue by connormanning** [connormanning/entwine#204]
Since 2.0, lots of useful things like performance optimizations, new encoding type Zstandard, removal of some dependencies, broader CI testing and related fixes, and some quality-of-life updates have been added.  Planning on releasing a 2.1 this week after cleaning up a few outstanding issues.

- [x] Get upstream PDAL dockerfile in working order (and re-enable ubuntu CI)
- [x] Resolve #186 
- [x] Resolve #200 
- [x] Dockerfile fixup
- [x] CI fixup
- [x] Other immediate issues?

**Comment by connormanning** [comment]
The Entwine 2.1 release has been tagged: https://github.com/connormanning/entwine/releases/tag/2.1.0

Docker image `connormanning/entwine:2.1` has been created and the `:latest` tag updated.

Updated Conda package coming shortly.

**Comment by tomvantilburg** [comment]
Minor remark for building this release yourself: in order to build this relase of entwine, PDAL (1.9.1) should have been build with the non-default zstd compression (`cmake -DWITH_ZSTD=YES`).

**Comment by hobu** [comment]
Addressed in PDAL @ https://github.com/PDAL/PDAL/pull/2641
