### ISSUE TITLE
Error creating tileset.json for Cesium

### ISSUE THREAD

**Issue by icemagno** [connormanning/entwine#208]
I'm asking for help here:
https://gis.stackexchange.com/questions/332279/my-point-cloud-orientation-is-very-wrong

I'm trying to load a cloud point using Cesium and Entwine.

This is my code until now:

First I convert a LAS file to EPT using this tutorial but need to convert projection to EPSG:4978.

`entwine build -i https://data.entwine.io/red-rocks.laz -o ~/entwine/red-rocks-ept -r EPSG:4978`

Now I have an EPT folder. Lets convert it to Cesium 3D tiles:

`entwine convert -i ~/entwine/red-rocks-ept -o ~/entwine/red-rocks`

Now I have a folder with Cesium files.

Lets serve them. I'll use docker but any http server will do it well. Don't forget to allow CORS:

```
docker run -it -v ~/entwine/cesium:/var/www -p 8080:8080 \
    connormanning/http-server

```
Now in Cesium:

```
var tileset = scene.primitives.add(new Cesium.Cesium3DTileset({
     url : 'http://YOUR_SERVER:8080/red-rocks/tileset.json',
}));    


tileset.readyPromise.then(function(tileset) {
    camera.viewBoundingSphere(tileset.boundingSphere, new Cesium.HeadingPitchRange(0, -0.5, 0));
    camera.lookAtTransform(Cesium.Matrix4.IDENTITY);        
}); 
```
My cloud is floating or lost somewhere in space.

This is a sample of my generated `tileset.json`:

> {"asset":{"version":"1.0"},"geometricError":27.75,"root":{"boundingVolume":{"box":[482412.0,4390630.0,1937.0,444.0,0,0,0,444.0,0,0,0,444.0]},"children":[{"boundingVolume":{"box":[482190.0,4390408.0,1715.0,222.0,0,0,0,222.0,0,0,0,222.0]},"children":[{"boundingVolume":{"box":[482301.0,4390297.0,1826.0,111.0,0,0,0,111.0,0,0,0,111.0]}

And this is a sample of the `tileset.json` of yours (from here: http://cesium.entwine.io/?url=http://cesium.entwine.io/data/red-rocks/tileset.json )

> {"asset":{"version":"1.0"},"geometricError":27.75,"root":{"content":{"uri":"0-0-0-0.pnts"},"boundingVolume":{"region":[-1.8362646096634487,0.6922201062740029,-1.8360843354356449,0.6923600711012987,1493,2381]},"geometricError":27.75,"refine":"ADD","children":[{"content":{"uri":"1-0-0-0.pnts"},"boundingVolume":{"region":[-1.8362646096634487,0.6922201062740029,-1.8361744777592646,0.6922900907024817,1493,1937]},"geometricError":13.875,"children":[{"content":{"uri":"2-1-0-1.pnts"},"boundingVolume":{"region":[-1.8362194405392143,0.6922201875220909,-1.8361743745767645,0.692255179239137,1715,1937]},"geometricError":6.9375,"children":[{"content":{"uri":"3-2-0-3.pnts"}

Why this is different and how this file was generated?

**Comment by connormanning** [comment]
Before you get to far into the weeds with this specific method of conversion, can you take a look at a new software package that I haven't publicized very much yet: [ept-tools](https://github.com/connormanning/ept-tools).  I'd like this to become the preferred method for doing 3D Tiles conversion in the near future.

The pieces that may interest you are the `serve` tool for real-time transformation from EPT to 3D-Tiles, and the `tile` tool for a one-time on-disk transformation - similar to what `entwine convert` currently does.  There are docs for each of these tools in the readme.

Note that a major benefit of the EPT Tools method over `entwine convert` is that your data does *not* need to be reprojected to EPSG:4978 during `entwine build` - it can work as long as your data has an EPSG code which can be mapped to a proj4js string.

You'd be one of the first users of this package, so feel free to submit any issues you encounter.

**Comment by icemagno** [comment]
Ha! I speak portuguese and find very funny  the `get to far into the weeds` part. At first look I took it  as literal. 

Well... I'm using this method because it is the official way to do it as long as know. 

I am still curious about the difference between the json found in demo  and the one I generated. What the method have you used? 

Anyway... I'll  try your new tool but I'll be very happy ir you "translate" the method I show here to the needed by ept-tools.

Another thing: I've checked my LAS file using pdal and noticed it have no projection information. Looking the coordinates  I think it is using some Brasilian UTM South and 23. I don't know if I can force  the srs even after checked the BB is from the region I know the LAS file is and if I do some mistake forcing the srs will mess all  the things.

Thanks very much for your patience.

**Comment by icemagno** [comment]
Update. I'm now using `ept-tools`. It seems to work beautifuly. Actually I put it in a Docker image together `entwine`. 

The red-rocks now is working in my own map but my LAS file don't. It is strange because when I put it in `http://cesium.entwine.io` it works... After some hours trying my own code (nothing special) 
I decided to copy the code in `http://cesium.entwine.io` page. Same error: my point cloud is floating somewhere in space. This is the code I'm using now:

	var tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
	     url : 'http://sisgeodef.defesa.mil.br:36300/congonhas-ept/ept-tileset/tileset.json',
	}));	
	
    tileset.style = new Cesium.Cesium3DTileStyle({
        pointSize: 3
    });

    tileset.readyPromise.then(function() {
        tileset.pointCloudShading.attenuation = true
        console.log('Loaded tileset');
        viewer.zoomTo(tileset)
    })
    .otherwise(function(error){
        console.log(error)
    });
	
in my own server this cause the points to go to space and when I point to `http://cesium.entwine.io/?url=http://sisgeodef.defesa.mil.br:36300/congonhas-ept/ept-tileset/tileset.json` ( same source ) its working. Well... not working very good because the points as a little below the terrain. But `viewer.zoomTo(tileset)` is leading to the correct position instead the outer space. Very strange.

Remember that I've forced the SRS in my LAS file and I'm not sure the correct projection it is. I can't talk to the file owner until now.

IMHO aside my problems the `ept-tools` is working fine. Simple to install and use. Fast. Elegant.

**Comment by icemagno** [comment]
After all I discovered the problem is my Cesium verion. I'm using the SuperMap iEarth one and they have the S3M format to do the same job. I don't know how to solve this....

**Comment by connormanning** [comment]
Closing since viewer.copc.io now handles this, so it's out of scope for Entwine.
