### ISSUE TITLE
Allow specification of storage of attributes as addon dimensions

### ISSUE THREAD

**Issue by hobu** [connormanning/entwine#209]
`GPSTime` is really heavy and almost never needed or visualized. While we need it for a completely lossless archive of the data, in many processing scenarios, it would be worthwhile to shunt it off to require another request to fetch it in the situations where we do. It would be helpful to update the EPT specification to clarify how addon dimensions are composed and update Entwine to allow configurations to specify how dimensions should be stored.

**Comment by connormanning** [comment]
Closing as out-of-scope for now, it's true that this would be useful in some cases but at the moment addons are still not a part of the EPT spec and are instead an application-level concept.
