### ISSUE TITLE
Add optional 'license' section to EPT specification

### ISSUE THREAD

**Issue by hobu** [connormanning/entwine#212]
The top-level of EPT needs an optional `license` entry added. Some other possible sub-elements might include

* `shortname` from https://spdx.org/licenses/
* `text` full text of license
* other fields as deemed necessary.

It would be nice to leverage existing standards work that describes how to communicate data licensing in this area, but there doesn't appear to be too much. Plenty of it in open source software land, but that's not quite the same thing.

**Comment by connormanning** [comment]
Perhaps this is better achieved through something like STAC pointing at EPT rather than within EPT itself.
