### ISSUE TITLE
Potree rise error with some CRSs in ept.json

### ISSUE THREAD

**Issue by luipir** [connormanning/entwine#224]
Not clear to me if the error is realted to Potree or how entwine create the CRS WKT in al ept*.json of the main build in in 0.json in ept-sources/ subdirectory

this WKT generate error:
  "srs": {
    "authority": "EPSG",
    "horizontal": "32630",
    "wkt": "COMPD_CS[\"GCS_WGS_1984\",PROJCS[\"WGS 84 / UTM zone 30N\",GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",0],PARAMETER[\"central_meridian\",-3],PARAMETER[\"scale_factor\",0.9996],PARAMETER[\"false_easting\",500000],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH],AUTHORITY[\"EPSG\",\"32630\"]],VERT_CS[\"unknown\",VERT_DATUM[\"unknown\",2005],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Up\",UP]]]"
  },

in:

VM250:1 Uncaught SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at b.exports (proj4.js:3)
    at Function.d [as defs] (proj4.js:1)
    at Function.computeAzimuth (utils.js:935)
    at Viewer.<anonymous> (Compass.js:23)
    at Viewer.dispatchEvent (EventDispatcher.js:93)
    at Viewer.update (viewer.js:1792)
    at Viewer.loop (viewer.js:2166)

I'll try to serve a data sample in a reliable server

**Comment by luipir** [comment]
entwine is used and installed in a conda environment. original data are generated with this workflow 

1) pdal translate -i ${file} -o "./morton_ordered/${filename}" --filter mortonorder
2) entwine build -i ./morton_ordered/ -o ./entwine/Avila/ --tmp ./temp_process/ --threads 1 -s $part $total_parts
3) and then entwine merge

**Comment by luipir** [comment]
happed also with another dataset generated with the same workflow... but no compound crs

thi sis the CRS that generate the issue:
  "srs": {
    "authority": "EPSG",
    "horizontal": "25829",
    "wkt": "PROJCS[\"ETRS89 / UTM zone 29N\",GEOGCS[\"ETRS89\",DATUM[\"European_Terrestrial_Reference_System_1989\",SPHEROID[\"GRS 1980\",6378137,298.257222101,AUTHORITY[\"EPSG\",\"7019\"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY[\"EPSG\",\"6258\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4258\"]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",0],PARAMETER[\"central_meridian\",-9],PARAMETER[\"scale_factor\",0.9996],PARAMETER[\"false_easting\",500000],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH],AUTHORITY[\"EPSG\",\"25829\"]]"
  },

**Comment by luipir** [comment]
The error is that the WKT passed to proj.defs is "EPSG:25829" and not a correct WKT => seems the problem is before, e..g in the place where ept reader get WKT string

**Comment by luipir** [comment]
the projection set in PointCloud geometry is set as epsg because gain in:
https://github.com/potree/potree/blob/develop/src/PointCloudEptGeometry.js#L57
respect:
https://github.com/potree/potree/blob/develop/src/PointCloudEptGeometry.js#L61

not clear to me what would be the best value to set proyection... IMHO the issue should be fixed just inverting these control... WKT would gain respect epsg:xxxx code

**Comment by luipir** [comment]
use fallbackProjection when calling proj.defs solve the problem... at least with https://github.com/connormanning/entwine/issues/224#issuecomment-590290310
Having more errors in https://github.com/connormanning/entwine/issues/224#issue-569805681

**Comment by connormanning** [comment]
Thanks for the report, looking into this.  Once we've got it figured out I'll update the bundled potree lib in https://github.com/connormanning/potree.entwine.io, which is quite out of date as you've noticed.

**Comment by luipir** [comment]
reported error in proj4.js lib https://github.com/proj4js/proj4js/issues/345

**Comment by luipir** [comment]
probably related with https://github.com/proj4js/proj4js/issues/282#issuecomment-359799285

**Comment by luipir** [comment]
probably I can override the issue of the compound CRS not supported by proj4js (https://github.com/connormanning/entwine/issues/224#issue-569805681) dong entwine build and forcing reprojection to a NO Compound crs.... o better fixing potree to extract planar projection and discarding In some way)  vertical one.

**Comment by luipir** [comment]
IMHO seems the error is more from the potree part to correctly manage sources more complex thatn a simple wkt (e.g. with EPSG code) or when a wkt is a compund projection

**Comment by connormanning** [comment]
Closing since this can be resolved in Potree, or can be worked around via Entwine by reprojecting the data so something that Potree understands.
