### ISSUE TITLE
Unhelpful message on S3 authentication failure

### ISSUE THREAD

**Issue by reinvantveer** [connormanning/entwine#225]
Hope to contribute to your efforts with the following bug report. The `entwine merge` command can (obviously) fail on unsuccesfully authenticating to a S3-protocol bucket. So, if you have a config.json being
```json
{
    "output": "s3://your_bucket/ept-subsets/",
    "verbose": true,
    "threads": [2, 5],
    "arbiter": {
        "s3": {
            "endpoint": "storage.googleapis.com",
            "access": "wrong",
            "secret": "wrong again!"
        }
    } 
}
```
the command
`entwine merge -c config.json` exits with:
```
Encountered an error: Dimension not found: 1
Exiting.
```
Expected output, something in the order of:
```
Encountered an error: Authentication failure
Exiting.
```
---
Using entwine 2.1.0:
```
root@62be9ee840f1:/app# entwine --version
Invalid app type
    Version: 2.1.0
    Usage: entwine <app> <options>
    Apps:
        build
            Build an EPT dataset
        scan
            Aggregate information about an unindexed dataset
        merge
            Merge colocated entwine subsets
        convert
            Convert an entwine dataset to a different format
```

**Comment by calvinmetcalf** [comment]
When I try something similar on `2.1.0` on linux, installed with conda I get `Encountered an error: No driver for s3://your_bucket/*` when I try to run a build.

**Comment by connormanning** [comment]
As mentioned above, the error message here should now be more helpful.
