### ISSUE TITLE
Last docker entwine updates : error :  

### ISSUE THREAD

**Issue by GuillaumePrecheur** [connormanning/entwine#23]
I just update my docker entwine image and get this entwine command error message whatever the docker run command I try to launch (ex :  docker run -it --rm connormanning/entwine /bin/bash)  
Is it a regression or did I miss something ??

> Invalid kernel type
>         Usage: entwine <kernel> <options>
>         Kernels:
>                 build
>                         Build (or continue to build) an index
>                 infer
>                         Aggregate information for an unindexed dataset
>                 merge
>                         Merge colocated previously built subsets
>

**Comment by connormanning** [comment]
I tweaked the dockerfile to (hopefully) simplify the invocation, adding an `entrypoint` of `entwine`.  Now the image name functions as the executable.

So instead of:
`docker run connormanning/entwine entwine build ...`

You would now run:
`docker run connormanning/entwine build ...`

**Comment by connormanning** [comment]
Closing this, if this does not resolve your issue feel free to re-open.
