### ISSUE TITLE
Error vector::_M_range_check : Unable to convert files with Entwine:2.1 (latest) while Entwine 2.0 works fine

### ISSUE THREAD

**Issue by AlbionS** [connormanning/entwine#232]
Hi,

I recently  noticed that the latest Entwine is not able to convert some files.
I think this has to do with the color. If it is coded with 8 or 16 bits.

_Errors encountered - data may be missing.  Errors:
        1 - /home/test.laz : vector::_M_range_check: __n (which is 64) >= this->size() (which is 64)_

It was really strange that Entwine2.0 was able to convert the file. I removed the color and Entwine2.1 was able to convert it too §

**The file that I used is this one :**  https://test-entwine-potree.s3.eu-west-3.amazonaws.com/test.laz (34.4 MB)

I have other files too if needed to reproduce the error.

Best,
Albion

-------------------------------------
P.S
And why does Entwine not convert all of the point clouds ? While viewing the result, most of the part are missing ? When I checked the last conversion I noticed that not all the points were converted !!!
Input:
        File: /home/xxx
        **Total points: 14,817,600**
        Density estimate (per square unit): 1642.82
        Threads: [3, 5]

Index completed in 1 seconds.
Save complete.
        **Points inserted: 45,056**

**Comment by AlbionS** [comment]
Actually even Entwine 2.0 does not work with some files. Same error 
![image](https://user-images.githubusercontent.com/29225486/88264923-e1170b80-cccc-11ea-8e59-3e303903c16c.png)

CloudCompare is able to read this file !

**Comment by AlbionS** [comment]
@connormanning  any news from this error ?

I did another test. I converted a file from e57 to las with pdal translate.
tried to convert this file with entwine 2.1 and 2.0. It shoes the same error.

The file I used is "PUMP.e57"

Entwine Version: 2.0.0
EPT Version: 1.0.0
Input:
        File: /home/pump_from_pdal.las
        **Total points: 2,878,964**
        Density estimate (per square unit): 97224.9
        Threads: [3, 5]
Output:
        Path: /home/pump_ent_from_pdal/
        Data type: laszip
        Hierarchy type: json
        Sleep count: 2,097,152
        Scale: 0.01
        Offset: (0, -3, 0)
Metadata:
        Bounds: [(-4, -6, -2), (3, 1, 2)]
        Cube: [(-6, -8, -5), (4, 2, 5)]
        Reprojection: (none)
        Storing dimensions: [
                X:int32, Y:int32, Z:int32, Intensity:uint16, ReturnNumber:uint8,
                NumberOfReturns:uint8, ScanDirectionFlag:uint8,
                EdgeOfFlightLine:uint8, Classification:uint8, ScanAngleRank:float,
                UserData:uint8, PointSourceId:uint16, GpsTime:double, Red:uint16,
                Green:uint16, Blue:uint16, OriginId:uint32
        ]
Build parameters:
        Span: 256
        Resolution 2D: 256 * 256 = 65,536
        Resolution 3D: 256 * 256 * 256 = 16,777,216
        Overflow threshold: 32,768

Adding 0 - /home/pump_from_pdal.las
        Pushes complete - joining...
**During /home/pump_from_pdal.las: vector::_M_range_check: __n (which is 64) >= this->size() (which is 64)**
        Done 0
Reawakened: 0
Saving registry...
Saving metadata...

Index completed in 2 seconds.
Save complete.
        **Points inserted: 32,768**

Converting this file with e572las.exe and then build the file, it works ! but not converting it with PDAL

**Comment by connormanning** [comment]
Closed by #308.
