### ISSUE TITLE
Unable to set source schema configuration

### ISSUE THREAD

**Issue by wonder-sk** [connormanning/entwine#234]
I am trying to build index with just a subset of dimensions as shown in the configuration example: https://entwine.io/configuration.html#schema

```json
{
    "schema": [
        { "name": "X", "type": "uint32" },
        { "name": "Y", "type": "uint32" },
        { "name": "Z", "type": "uint32" },
        { "name": "Intensity", "type": "int8" }
    ]
}
```

This aborts with an exception:
```
terminate called after throwing an instance of 'nlohmann::detail::out_of_range'
  what():  [json.exception.out_of_range.403] key 'size' not found
```

When I add `size` to each dimension (even though that should not be needed), that still does not work:
```json
  "schema": [
        { "name": "X", "type": "uint32", "size": 4 },
        { "name": "Y", "type": "uint32", "size": 4 },
        { "name": "Z", "type": "uint32", "size": 4 }
  ]
```
This will trigger a different exception, but I am not sure what's really wrong there or how to fix it:
```
Encountered an error: Invalid dimension specification: {
  "name": "X",
  "size": 4,
  "type": "uint32"
}
Exiting.
```

Changing `uint32` type to `float` makes things work.

So I see two related issues:
- it is unclear if `size` is required and whether the docs need updating or the code needs fixing
- being unable to use `uint32` when size is specified or not

**Comment by gsmercier** [comment]
Could it be a typo? 'Unit' instead of 'Uint'.
-G.

**Comment by wonder-sk** [comment]
It looks like JSON parsing is done here https://github.com/connormanning/entwine/blob/master/entwine/types/dimension.cpp#L20
...and the only allowed values for `type` are `unsigned`, `signed`, `float`, `floating`

**Comment by connormanning** [comment]
This should work with current code and the name/type/size specification of EPT as the `schema` dimensions.
