### ISSUE TITLE
Binary encoding of position not matching the schema

### ISSUE THREAD

**Issue by wonder-sk** [connormanning/entwine#240]
When I run entwine with `binary` output data type, serialized data does not seem to match the schema in ept.json.

Using this file as input: http://maps.zh.ch/download/hoehen/2014/lidar/26850_12580.laz

I am running Entwine (master branch @ cec177cfe020a01696740cb133f5a339619603cb) with this command:

```
$ entwine build -i ~/tmp/las/26850_12580.laz -o /tmp/test-binary --dataType binary
```

Encoded data of the root node: [0-0-0-0.bin.zip](https://github.com/connormanning/entwine/files/5378088/0-0-0-0.bin.zip)

The root node should contain 27135 points (from ept-hierarchy) and the size of binary data of the root node is 1248210 bytes... that's 46 bytes per point. However the sum of sizes of dimensions in ept.json I was expecting 34 bytes per point. I have realized the difference is caused by X,Y, Z dimensions being encoded as 64-bit floats instead of 32-bit floats as declared in the schema.

Relevant parts of ept.json (removed stats for each dimension for brevity):

```
  "schema": [
    {
      "name": "X",
      "offset": 2685250,
      "scale": 0.01,
      "size": 4,
      "type": "signed",
    },
    {
      "name": "Y",
      "offset": 1258250,
      "scale": 0.01,
      "size": 4,
      "type": "signed",
    },
    {
      "name": "Z",
      "offset": 952,
      "scale": 0.01,
      "size": 4,
      "type": "signed",
    },
    {
      "name": "Intensity",
      "size": 2,
      "type": "unsigned",
    },
    {
      "name": "ReturnNumber",
      "size": 1,
      "type": "unsigned",
    },
    {
      "name": "NumberOfReturns",
      "size": 1,
      "type": "unsigned",
    },
    {
      "name": "ScanDirectionFlag",
      "size": 1,
      "type": "unsigned",
    },
    {
      "name": "EdgeOfFlightLine",
      "size": 1,
      "type": "unsigned",
    },
    {
      "name": "Classification",
      "size": 1,
      "type": "unsigned",
    },
    {
      "name": "ScanAngleRank",
      "size": 4,
      "type": "float",
    },
    {
      "name": "UserData",
      "size": 1,
      "type": "unsigned",
    },
    {
      "name": "PointSourceId",
      "size": 2,
      "type": "unsigned",
    },
    {
      "name": "GpsTime",
      "size": 8,
      "type": "float",
    }
  ],
```

**Comment by connormanning** [comment]
Fixed in 56405b5c31b7678d90b75359258ff168431786b7.
