### ISSUE TITLE
Configuration file issue

### ISSUE THREAD

**Issue by mixadrone** [connormanning/entwine#246]
Hi.
I tried run build module with json configuration file and it not works on the some files, but if i run with string args it works.
Here is json config file
`{
    "input": "Z:/Viaduct/clipped2/clipped_1-10.laz",
    "output": "Z:/Viaduct/clipped2/clipped_1-10_2",
    "reprojection": {
        "in": "EPSG:28355",
        "out": "EPSG:4987",
	"hammer": true
    },
    "threads": 12,
    "scale": 0.001,
    "span": 256
}`

Here is output in Conda:

Output with configuration file
----------------------------------

(entwine) C:\Users\admin>entwine build -c Z:\Viaduct\clipped2\4.json
Scanning input
1/1: Z:/Viaduct/clipped2/clipped_1-10.laz

Entwine Version: 2.1.0
EPT Version: 1.0.0
Input:
        File: Z:/Viaduct/clipped2/clipped_1-10.laz
        Total points: 255,853,116
        Density estimate (per square unit): 3.74548e+14
        Threads: [1, 11]
Output:
        Path: Z:/Viaduct/clipped2/clipped_1-10_2/
        Data type: laszip
        Hierarchy type: json
        Sleep count: 2,097,152
        Scale: 0.001
        Offset: (145, -38, 12)
Metadata:
        SRS: EPSG:4987
        Bounds: [(144, -38, 1), (145, -37, 23)]
        Cube: [(133, -50, 0), (157, -26, 24)]
        Reprojection: EPSG:28355 (FORCED) -> EPSG:4987
        Storing dimensions: [
                X:int32, Y:int32, Z:int32, Intensity:uint16, ReturnNumber:uint8,
                NumberOfReturns:uint8, ScanDirectionFlag:uint8,
                EdgeOfFlightLine:uint8, Classification:uint8, ScanAngleRank:float,
                UserData:uint8, PointSourceId:uint16, Red:uint16, Green:uint16,
                Blue:uint16, OriginId:uint32
        ]
Build parameters:
        Span: 256
        Resolution 2D: 256 * 256 = 65,536
        Resolution 3D: 256 * 256 * 256 = 16,777,216
        Maximum node size: 262,144
        Minimum node size: 65,536
        Cache size: 64

Adding 0 - Z:/Viaduct/clipped2/clipped_1-10.laz
        Pushes complete - joining...
00:10 - 1% - 3,354,624 - 1,207(1,207)M/h - 0W - 0R - 33A
00:20 - 3% - 6,467,584 - 1,164(1,120)M/h - 0W - 0R - 63A

(entwine) C:\Users\admin>

=======================================================
Output with the same parameters as string arguments
--------------------------------------------------------------------------------------------
(entwine) C:\Users\admin>entwine build -i Z:/Viaduct/clipped2/clipped_1-10.laz -o Z:/Viaduct/clipped2/clipped_1-10 -r EPSG:28355 EPSG:4978 -h -t 12 --scale 0.001 --span 256
Scanning input
1/1: Z:/Viaduct/clipped2/clipped_1-10.laz

Entwine Version: 2.1.0
EPT Version: 1.0.0
Input:
        File: Z:/Viaduct/clipped2/clipped_1-10.laz
        Total points: 255,853,116
        Density estimate (per square unit): 21379.5
        Threads: [1, 11]
Output:
        Path: Z:/Viaduct/clipped2/clipped_1-10/
        Data type: laszip
        Hierarchy type: json
        Sleep count: 2,097,152
        Scale: 0.001
        Offset: (-4130022, 2896766, -3889792)
Metadata:
        SRS: EPSG:4978
        Bounds: [(-4130074, 2896708, -3889824), (-4129970, 2896824, -3889760)]
        Cube: [(-4130081, 2896707, -3889851), (-4129963, 2896825, -3889733)]
        Reprojection: EPSG:28355 (FORCED) -> EPSG:4978
        Storing dimensions: [
                X:int32, Y:int32, Z:int32, Intensity:uint16, ReturnNumber:uint8,
                NumberOfReturns:uint8, ScanDirectionFlag:uint8,
                EdgeOfFlightLine:uint8, Classification:uint8, ScanAngleRank:float,
                UserData:uint8, PointSourceId:uint16, Red:uint16, Green:uint16,
                Blue:uint16, OriginId:uint32
        ]
Build parameters:
        Span: 256
        Resolution 2D: 256 * 256 = 65,536
        Resolution 3D: 256 * 256 * 256 = 16,777,216
        Maximum node size: 262,144
        Minimum node size: 65,536
        Cache size: 64

Adding 0 - Z:/Viaduct/clipped2/clipped_1-10.laz
        Pushes complete - joining...
00:10 - 2% - 4,304,896 - 1,549(1,549)M/h - 0W - 0R - 33A
00:20 - 3% - 8,790,016 - 1,582(1,614)M/h - 0W - 0R - 62A
00:30 - 5% - 13,176,832 - 1,581(1,579)M/h - 0W - 0R - 90A
.......
22:40 - 98% - 250,867,712 - 664(911)M/h - 12W - 12R - 124A
22:50 - 99% - 253,440,000 - 665(926)M/h - 21W - 9R - 126A
23:00 - 100% - 255,853,116 - 667(868)M/h - 30W - 10R - 132A
        Done 0
Reawakened: 2561
Saving registry...
23:10 - 100% - 255,853,116 - 662(0)M/h - 121W - 0R - 7A
Saving metadata...

Index completed in 23:17.
Save complete.
        Points inserted: 255,853,116

(entwine) C:\Users\admin>

**Comment by connormanning** [comment]
This should work as expected with current code.
