### ISSUE TITLE
entwine build:   SIGSEGV 

### ISSUE THREAD

**Issue by waybarrios** [connormanning/entwine#250]
I have tried to create a dataset from 120 las files, but I always got this  SIGSEGV excemption. 

Any suggestions?

**Comment by waybarrios** [comment]
Scanning input
1/1: /code/lidar/20PPC6610017190.las
(readers.las Error) Global encoding WKT flag not set for point format 6 - 10.
(readers.las Error) Global encoding WKT flag not set for point format 6 - 10.
SRS could not be determined

Entwine Version: 2.1.0
EPT Version: 1.0.0
Input:
	File: /code/lidar/20PPC6610017190.las
	Total points: 8,337,972
	Density estimate (per square unit): 9.16129
	Threads: [1, 7]
Output:
	Path: /code/lidar/test/
	Data type: laszip
	Hierarchy type: json
	Sleep count: 2,097,152
	Scale: 0.01
	Offset: (661545, 1719500, 128)
Metadata:
	SRS: (none)
	Bounds: [(661089, 1718999, -64), (662000, 1720000, 321)]
	Cube: [(661043, 1718998, -373), (662047, 1720002, 631)]
	Storing dimensions: [
                X:int32, Y:int32, Z:int32, Intensity:uint16, ReturnNumber:uint8,
                NumberOfReturns:uint8, ScanDirectionFlag:uint8,
                EdgeOfFlightLine:uint8, Classification:uint8, ScanAngleRank:float,
                UserData:uint8, PointSourceId:uint16, GpsTime:double,
                ScanChannel:uint8, ClassFlags:uint8, OriginId:uint32
	]
Build parameters:
	Span: 128
	Resolution 2D: 128 * 128 = 16,384
	Resolution 3D: 128 * 128 * 128 = 2,097,152
	Maximum node size: 65,536
	Minimum node size: 16,384
	Cache size: 64

Adding 0 - /code/lidar/20PPC6610017190.las
	Pushes complete - joining...
(readers.las Error) Global encoding WKT flag not set for point format 6 - 10.
[1]    10348 segmentation fault (core dumped)  entwine build -i /code/lidar/20PPC6610017190.las -o /code/lidar/test

**Comment by waybarrios** [comment]
I got this one, Does anyone know what is going on here?

**Comment by waybarrios** [comment]
@connormanning

**Comment by hobu** [comment]
You'll probably need to post the file to inspect somewhere.

**Comment by waybarrios** [comment]
https://drive.google.com/file/d/1pE3ghtZ0thohTGDpjb6alW42Xk0ndvV0/view?usp=sharing @hobu

**Comment by connormanning** [comment]
Closed by #308.
