### ISSUE TITLE
Crash on building cesium tiles with coloring:intensity

### ISSUE THREAD

**Issue by tomvantilburg** [connormanning/entwine#26]
Latest PDAL and Entwine (today's build).

Report:
```
Adding 0 - /tmp/118100-485100-118200-485200/pointcloud.las
 A: 0 C: 1 H: 3
        Pushes complete - joining...
Found an SRS
terminate called after throwing an instance of 'pdal::pdal_error'
  what():  Unable to fetch data and convert as requested: Intensity:uint16_t(15865) -> unsigned char
Aborted (core dumped)
```

Pointcloud: 
[http://research.geodan.nl/sites/cesium/data/pointcloud.tar.gz](http://research.geodan.nl/sites/cesium/data/pointcloud.tar.gz)

Entwine config:
```
{
    "absolute": true,
    "reproject": {
        "out": "EPSG:4978"
    },
    "formats": {
        "cesium": {
            "tilesetSplit": 8,
            "coloring": "intensity",
            "geometricErrorDivisor": 16.0
        }
    }
}
```

This only happens when choosing "coloring":"intensity". "coloring":"tile" or no coloring at all works correct. Previous version of entwine gave only 'black' color on intensity.

**Comment by connormanning** [comment]
The RGB values for 3d-tiles are [8-bit values](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/PointCloud#point-semantics), so setting them equal to intensity, when intensity is greater than 255, will cause this error.  For now you should be able to resolve this by shifting your intensity values into the 8-bit range before running Entwine.

However, Entwine probably should have something like `--clamp-intensity` and `--clamp-color` options.  Aside from Cesium output, some clients might also prefer 8-bit color/intensity fields and would like this transformation.

**Comment by tomvantilburg** [comment]
8-bit values seem a reasonable take on coloring. Would be nice to document (I can do a pull request if you like). For now I used the [colorinterp](http://www.pdal.io/stages/filters.colorinterp.html) filter from PDAL, that works fine and I think I'll stick to it for my coloring.
Maybe entwine doesn't even need to bother itself with color conversions since PDAL can handle it nicely?

**Comment by aleksandrmelnyk** [comment]
Hey guys,

sorry, but you got working that pdal.colorinterp? 
Am using following PDAL pipeline:

```
{
  "pipeline":[
	 {
      "type":"readers.las",
      "filename":"/opt/data/e3085n69655.laz",
	  "compression": "laszip"
    },
    {
	 "type": "filters.colorinterp",
      "minimum":0,
      "maximum":255,
	  "dimension":"Red"
    },
	{
	 "type": "filters.colorinterp",
      "minimum":0,
      "maximum":255,
	  "dimension":"Green"
    },
	{
	 "type": "filters.colorinterp",
      "minimum":0,
      "maximum":255,
	  "dimension":"Blue"
    },
	{
      "type":"writers.las",
      "filename":  "/opt/data/colorized.laz",
	  "compression": "laszip"
    }
  ]
}
```
and the output file (colorized.laz) stay extacly same as input, the filters are just ignored.

thanks,

Alex.

**Comment by aleksandrmelnyk** [comment]
Are there any other solutions apart from the PDAL filter (excluding writing custom app)?

**Comment by aleksandrmelnyk** [comment]
In case someone would face such issue, here working solution for me:
1. use [ filters.programmable](https://www.pdal.io/stages/filters.programmable.html)
2. write python script as below:
```
import numpy as np

def cast_type(ins, outs):
    #outs = ins
    Red = ins['Red']
    Green = ins['Green']
    Blue = ins['Blue']

    outs['Red'] = (255*Red.astype(int)/65535).astype(np.uint16)
    outs['Green'] = (255*Green.astype(int)/65535).astype(np.uint16)
    outs['Blue'] = (255*Blue.astype(int)/65535).astype(np.uint16)

    return True
```

3. use following pipeline for PDAL:
```
{
  "pipeline":[
	 {
      "type":"readers.las",
      "filename":"/opt/data/e2895n69635.laz",
	  "compression": "laszip"
    },
	{
	  "type":"filters.programmable",
	  "script":"/opt/options/filter.py",
	  "function":"cast_type",
	  "module":"anything"
	},
	{
      "type":"writers.las",
      "filename":  "/opt/data/colorized.laz",
	  "compression": "laszip"
    }
  ]
}
```
4. run pdal pipeline:

> docker run -it -v h:/arrow_laz:/opt/data -v h:/arrow_laz_index:/opt/options pdal/pdal:1.5 pdal pipeline /opt/options/filter.json

after that the 3d-tile will be generated by the entwine command

thanks,

Alex.

**Comment by cherukumilli** [comment]
@aleksandrmelnyk 
I am running a problem using your instructions above.

I see the following error: 
`PDAL: 'Traceback (most recent call last):\n''  File "anything", line 5, in cast_type\n'"KeyError: 'Red'\n"`

Any help troubleshooting this problem will be greatly appreciated. 

btw: `filters.programmable` has been changed to `filters.python` since your last update.

my `filter.python.json` pipeline file is:
```{
  "pipeline":[
    {
      "type":"readers.las",
      "filename":"/input/classified_lidar.las"
    },
    {
      "type":"filters.python",
      "script":"/scripts/filter.py",
      "function":"cast_type",
      "module":"anything"
    },
    {
      "type":"writers.las",
      "filename":  "/output/classified_lidar_colorized.las"
    }
  ]
}
```

and my python script is:
