### ISSUE TITLE
entwine build issues on Windows 10

### ISSUE THREAD

**Issue by SkylerBleu** [connormanning/entwine#261]
Whenever running the build command from a windows machine, nothing is currently happening. For example:

```entwine build -i ./points.las -o ./3D/entwine -r EPSG:4978```

On windows outputs the following:
```
Scanning input
1/1: ./points.las
```

This same command/file combination is working fine on Macbook

Another thing to note is removing ```-r EPSG:4978``` actually starts the process, but it stops after generating the output folders. No data is actually created though. Specifically stops at 16%.

**Comment by connormanning** [comment]
This should be working now, and CI is also running on Windows so we should be able to notice if it breaks there.
