### ISSUE TITLE
nlohmann JSON parsing of config throws std::exception, entwine main catches std::runtime_error.

### ISSUE THREAD

**Issue by tfiner** [connormanning/entwine#264]
Reproduction:
Pass in an invalid JSON to entwine's config.

Observation:
Entwine crashes with an unhandled C++ exception.  On windows, an unhandled exception causes the Just in Time Debugger to launch (if there is one installed).

Expectation:
That invalid JSON would show whatever the JSON library didn't like about the passed in JSON.

Details:
Nlohmann's JSON parser throws a std::exception via the JSON_THROW macro.  Entwine's main is looking for a too-specific and a wrong kind of exception: std::runtime_error.  If you change the catch in main to catch std::exception instead this will catch all exceptions derived from std::exception (also a best practice).  This also future proofs the catch for all kinds of other std::exception derivatives.

**Comment by hobu** [comment]
Please make a PR fixing this and we can merge it.

**Comment by tfiner** [comment]
Done.
