### ISSUE TITLE
libcrypto-3-x64.dll missing on Windows

### ISSUE THREAD

**Issue by PhilippeD31** [connormanning/entwine#267]
With Entwine 2.2.0 on Windows 10, when I try an "entwine build ...", I get an error message : "libcrypto-3-x64.dll" is missing.

That DLL is part of OpenSSL 3.0. But OpenSSL 1.1.1 is installed by Anaconda (or Entwine package).  
And impossible to install OpenSSL 3.0.0 (from conda-forge) on Anaconda3 : many conflicts!  
I tried to force the installation. But it failed.

Is there an way to make "entwine build" work with OpenSSL 1.1.1?

**Comment by hobu** [comment]
It's feedstock needs to be updated with an OpenSSL dependency and it needs to be rerendered.

**Comment by PhilippeD31** [comment]
Thanks for the quick answer.  
I'm not familiar with Anaconda. To update the feedstock, is it something I can do? And how?

**Comment by hobu** [comment]
It has been done. Please test and repull

**Comment by PhilippeD31** [comment]
Thank you. I will update Entwine and test the buid command after the holidays.  
Regards

**Comment by PhilippeD31** [comment]
Problem solved!  

At fist I runned the command: "conda update entwine"  
But I got the same error message with "entwine build ...": "libcrypto-3-x64.dll" is missing.  
So I completely uninstalled entwine, and then did: "conda create -n entwine -c conda-forge entwine".  

Now "entwine build" works fine.  Thank you!
