### ISSUE TITLE
using deprecated flags throws error rather than warning

### ISSUE THREAD

**Issue by Crghilardi** [connormanning/entwine#279]
I ran into this trying to port some code that happen to use `--noTrustHeaders` up to entwine `2.2.0`
MWE:
```
#conda create --name entwine-220-env
#conda activate entwine-220-env
#conda install -y -c conda-forge entwine=2.2.0

$ entwine info --noTrustHeaders
Encountered an error: Invalid argument: --noTrustHeaders
Exiting.
```
It looks like there is some kind of [deprecation warning](https://github.com/connormanning/entwine/blob/master/app/entwine.cpp#L171-L185). I guess I would expect using those flags to throw the message and switch to `deep` behind the scenes rather than an error. Is this correct behavior?

Also, is there a place where all the deprecated flags are listed? I did not see anything in Release notes, I ended up downloading a couple different versions and running `entwine scan --help` to figure out when options got dropped.

**Comment by connormanning** [comment]
Probably this should have been done in a major release rather than a minor (and the next release will be a major), but you are correct that this history isn't explicitly listed in a doc at the moment.  This would be a good idea to track starting with 3.0.
