### ISSUE TITLE
z-offset in cesium tiles

### ISSUE THREAD

**Issue by tomvantilburg** [connormanning/entwine#28]
There is an unexplainable positive z-offset in the output of the cesium tiles (in cesium viewer).
In this image you see the pointcloud floating above another set of vector tiles:
![image](https://cloud.githubusercontent.com/assets/1998463/22288433/28439366-e2f7-11e6-83e9-92b24f1b1b45.png)

Things I checked:
- proper coordinate system is given with las file (EPSG:28992), including towgs params
- other cesium vector tiles originating from the same srs are working well (as can be seen in the image)
- X and Y seem well aligned, only z

I also compared the transform matrix given in the tileset.json from entwine with the one that would be calculated by cesium based on the minx, miny values from the las file with:
```
var matrix = Cesium.Transforms.eastNorthUpToFixedFrame(Cesium.Cartesian3.fromDegrees(4.84539353916,52.3523793903,-2.219))
```
resulting in these differences:
Entwine transform:
```
 [
         -0.084535880369591351,	0.99642043582522855,	-6.9388939039072299e-18,	0,
         -0.78699076737683538,	-0.066767957551816193,	0.61334131762663679,		0,
         0.61114582301915321,	0.051849348252612899,	0.78981797149217947,		0,
         3889839.5983011033,	330012.31519960327,		5027057.5454196455,			1
  ]
```
Cesium tranform:
```
[
	-0.08446730511458142, 0.9964262513436106, 0, 0, 
 	-0.7889526244257994, -0.06687971333399081, 0.6108034547675762, 0, 
 	0.6086205967417826, 0.05159292177889329, 0.7917822551964607, 0, 
 	3890035.6951631806, 329759.3088569205, 5026846.2020282885, 1
 ]
```
I was hoping the cesium transform would be correct (it is for the vector data you can see in the image) but unfortunately although clamping the pointset to the ground it introduces an offset in -X and -Y direction of some 200 meters. Also I'm not sure if the problem is really in the transform matrix or already happens in the reprojection in entwine.
**Worth noting**: a large part of the points is below sea level and have a negative z-value.

The corresponding las file can be found at: [http://research.geodan.nl/sites/cesium/data/pointcloud.tar.gz](http://research.geodan.nl/sites/cesium/data/pointcloud.tar.gz)

**Comment by connormanning** [comment]
Thanks for uploading the file - I've taken a look.  I've hosted my results [here](http://cesium.entwine.io/?resource=elevation-issue) although I imagine they are the same as yours.  I notice that the data seems to match perfectly against the "STK World Terrain Meshes" offered by Cesium, but that it does indeed float above the WGS84 ellipsoid, as you've seen.  To me this seems to imply that the vertical datum of the source data might not match what you want, if you want it pinned to the WGS84 ellipsoid.  My knowledge on this is pretty minimal, but I think that currently Entwine's Cesium output will preserve the elevation of the input, be it geoid or ellipsoid.

One other note about cesium.entwine.io - it loads with the STK terrain mesh terrain initially, however the terrain button will as WGS84.  So if you want to switch to WGS84 you'll need to select STK and then back to WGS84.

**Comment by tomvantilburg** [comment]
You're right @connormanning, and looking a bit further it can also be seen in the las file:
This is what `las info` tells me (note the difference in min and max for z, there is a roughly 40 meters offset):
```
"stats":
  {
"bbox":
    {
      "EPSG:4326":
      {
        "bbox":
        {
          "maxx": 4.853337623,
          "maxy": 52.35717586,
          "maxz": 76.9866723,
          "minx": 4.845335447,
          "miny": 52.35237938,
          "minz": 40.70801498
        },
 }, ...
      "native":
      {
        "bbox":
        {
          "maxx": 118627.09,
          "maxy": 485609.33,
          "maxz": 33.98,
          "minx": 118085.83,
          "miny": 485079.65,
          "minz": -2.29
        },

```

So nothing to do with Entwine, but thanks a lot for looking into it!
