### ISSUE TITLE
Docker images are not versioned

### ISSUE THREAD

**Issue by dhardestylewis** [connormanning/entwine#289]
Docker images with version tags are not actually building against that release

Line 4 in version 2.2.0's Dockerfile refers to the master branch instead of the version 2.2.0 release:
https://github.com/connormanning/entwine/blob/49ad52f985536cb8987d079402377cac50360cf3/scripts/docker/Dockerfile#L4

This can also be seen in the build commands on DockerHub:
https://hub.docker.com/layers/connormanning/entwine/2.2.0/images/sha256-669bd97560c92e6f7ff13b1b575831220639fc6c2638f6c8c1be66454776e49d?context=explore

I have fixed this in my fork:
https://github.com/dhardestylewis/entwine/blob/e23a8c1056958e68eff2477c09cf2e3a3a51caa0/scripts/docker/Dockerfile

and my DockerHub image of version 2.2.0:
https://hub.docker.com/layers/dhardestylewis/entwine/2.2.0/images/sha256-93d84fc5266e5c7269cb30c4eb3dc95d59265845ad5c418944fcd115a7f345d8?context=explore

**Comment by connormanning** [comment]
Currently the only officially supported release channel is Conda - so the Dockerfile should be used just for an example.
