### ISSUE TITLE
Assertion failure with repeated points in point cloud

### ISSUE THREAD

**Issue by z-mach9** [connormanning/entwine#290]
Hi,

I'm running `entwine build --input geo.las --output tiles` and getting the following assertion failure (link to [geo.las](https://mach9-public.s3.amazonaws.com/entwine-assertion-failure/geo.las), it's 5.4GB):

```
entwine: /home/z/repository/entwine/entwine/builder/chunk-cache.cpp:70: void entwine::ChunkCache::insert(entwine::Voxel&, entwine::Key&, const entwine::ChunkKey&, entwine::Clipper&): Assertion `ck.depth() < maxDepth' failed.
```

The file `geo.las` has a few stretches of points with all identical X-Y-Z values.  Running `entwine build` on a subset of `geo.las` consisting of only those points (e.g. [split_3_1_5_5.las](https://mach9-public.s3.amazonaws.com/entwine-assertion-failure/split_3_1_5_5.las), it's 6.2MB) hits the same assertion failure.  

GDB output from the assertion failure:
[entwine-gdb-output.txt](https://github.com/connormanning/entwine/files/9708851/entwine-gdb-output.txt)

**Comment by hobu** [comment]
> The file geo.las has a few stretches of points with all identical X-Y-Z values. 

Entwine doesn't support infinite depth trees. A scanner sitting in one area piling up points is functionally creating those. You could try increasing the [maxDepth parameter](https://github.com/connormanning/entwine/blob/master/entwine/types/defs.hpp.in#L52) and recompiling, but that's going to push the problem down the road. IMO you're better off filtering those points that are likely junk before pushing them into your tree.

No bug in Entwine here, as it is working as designed.

**Comment by connormanning** [comment]
[Untwine](https://github.com/hobuinc/untwine) would probably work fine with this data though, due to its different sampling method from Entwine.

**Comment by z-mach9** [comment]
Thanks for the clarification!  I'll filter these points out before tiling then.
