### ISSUE TITLE
Windows executables

### ISSUE THREAD

**Issue by Pourfex** [connormanning/entwine#297]
Hello,
We've been trying to make an executable for Windows of Entwine to convert las,e57,laz to ept file format. 

We tried many things as non-python expert and we might be missing something and failed.

Is there any way you can help us on doing some executables and share them with the community ? For testing purposes of the EPT format it'll be great.

**Comment by hobu** [comment]
Untwine https://github.com/hobuinc/untwine is probably better for the scenario where you want to build EPT with windows.

It is available via Conda Forge https://anaconda.org/conda-forge/untwine. See the recipes in the untwine feedstock for inspiration how to build it as a windows executable
