### ISSUE TITLE
missing libpdal_base.so.13

### ISSUE THREAD

**Issue by NimaEkhtari** [connormanning/entwine#307]
running a basic entwine build statement results in the following error. 
**entwine: error while loading shared libraries: libpdal_base.so.13: cannot open shared object file: No such file or directory**

Tested on Linux Ubuntu 22.04.2
I use conda for package management. 
Entwine version 2.2.0
pdal version 2.5.1

**Comment by hobu** [comment]
We need to have a new Entwine version. Things were moving that direction but have stalled a bit. I don't have a timeline for you.
