### ISSUE TITLE
Compilation Error Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by eokeeffe** [connormanning/entwine#31]
Hey dude
Just tried compiling the package from the master branch

Had some compilation issues surrounding laszip

             from /home/evan/Libraries/entwine/entwine/util/executor.cpp:22:
/usr/local/include/pdal/io/LasZipPoint.hpp:40:22: fatal error: laszip.hpp: No such file or directory
compilation terminated.
entwine/util/CMakeFiles/util.dir/build.make:86: recipe for target 'entwine/util/CMakeFiles/util.dir/executor.cpp.o' failed
make[2]: *** [entwine/util/CMakeFiles/util.dir/executor.cpp.o] Error 1
CMakeFiles/Makefile2:474: recipe for target 'entwine/util/CMakeFiles/util.dir/all' failed
make[1]: *** [entwine/util/CMakeFiles/util.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

The fix was pretty easy, just added 
include_directories(/home/evan/Libraries/LAStools/LASzip/src/)

Had LAStools paired with PotreeConverter, followed their installation before
I found this.

Thought I'd leave that there as a fix for anyone with similar issues

**Comment by connormanning** [comment]
This should be fixed now in master via #30.
