### ISSUE TITLE
Does recursive directory increase entwine build time

### ISSUE THREAD

**Issue by Mboga** [connormanning/entwine#310]
Thank you for the great tool.
I have noticed that data providers of laz files might store their data in recursive directories ( e.g. more than 5 levels) while others in non-recursive directories.

I was wondering how the processing time for building an Entwine Point Tile through the `entwine build `command is impacted when the *.laz files are contained in a recursive directory `~/data/** `as opposed to a non-recursive directory  `~/data/*`.

Thank you for your response.

**Comment by connormanning** [comment]
I don't think this should cause any difference in performance - the input directories are only listed one time and afterwards only the full filenames are used.  If you find an issue here you can open a ticket with details.
