### ISSUE TITLE
Cannot read properties of undefined (reading 'wkt')

### ISSUE THREAD

**Issue by paujar** [connormanning/entwine#312]
The running of the script stops for this "Cannot read properties of undefined (reading 'wkt')" by the tutorial from here https://entwine.io/en/latest/quickstart.html

Also I installed potree entwine on my local machine and trying to run from there and I got same error:

![image](https://github.com/connormanning/entwine/assets/120630944/61edf41f-e758-45ec-b48a-ac58d03f4234)
![image](https://github.com/connormanning/entwine/assets/120630944/bced8335-5f43-43cb-8682-076921f3f96f)

Any idea why is that? I build the entwine output with current conda managed entwine version 3.0.0 and with potree version from here (./build/potree/) https://github.com/connormanning/potree.entwine.io/

**Comment by connormanning** [comment]
You can add `"srs": {}` to your `ept.json` file and it should work.
