### ISSUE TITLE
Unable to export as LAS 1.4

### ISSUE THREAD

**Issue by kcotar** [connormanning/entwine#313]
I noticed that the new entwine build version provides the option to export ept files as LAZ 1.4, but it does not work for me.

When running `entwine build --laz_14 true -i file.laz -o ent_14/` it gives error `Encountered an error: Error handling argument '--laz_14' with value "true": [json.exception.type_error.302] type must be number, but is boolean`.

This error suggests that it might have to be run as `entwine build --laz_14 1 -i file.laz -o ent_14/`, but this also does not work as created files are of format LAS 1.2, point format 3.

Using entwine 3.0.0 (installed version, reported version is 2.3.0) and pdal 2.6.0.

**Comment by connormanning** [comment]
This should be solved by 376589624b04735a9cfdba4ccabcba831e49eaa6, which will be released shortly.
