### ISSUE TITLE
Unable to export classes larger than 31

### ISSUE THREAD

**Issue by kcotar** [connormanning/entwine#314]
In the latest version, we noticed that exporting classes larger than 31 is not working as before in 2.2.0. For the test, I have an input LAS 1.4 file with point format 7 with random classification values from 1 to 255. In the latest version, all points that have a classification larger than 31 are set to the fixed value of 1. This leads me to believe that the problem is not in throwing away some bits during some data-type conversion, but an actual value remapping happens.

Can this be related to my other problem with exporting LAS 1.4 data? https://github.com/connormanning/entwine/issues/313

Using entwine 3.0.0 (installed version, reported version is 2.3.0) and pdal 2.6.0.

**Comment by connormanning** [comment]
This should be solved by 376589624b04735a9cfdba4ccabcba831e49eaa6, which will be released shortly.
