### ISSUE TITLE
Error when using schema option

### ISSUE THREAD

**Issue by flemmens** [connormanning/entwine#317]
Hello,

I would like to build an entwine directory containing only X,Y,Z dimensions. According to the documentation, I use the following config file:
```
{
    "input": "myfile.laz",
    "output": "mydir",
    "schema": [
        { "name": "X", "type": "uint32" },
        { "name": "Y", "type": "uint32" },
        { "name": "Z", "type": "uint32" }
    ]
}
```

But it returns the following error:
```
Encountered an error: [json.exception.out_of_range.403] key 'size' not found
```

If I remove the schema tag, everything works well.
Is it something wrong with my understanding ? How can I keep only some dimensions in the result tiles ?

Thanks

**Comment by connormanning** [comment]
Hmm, try this format instead: `{ "name": "X", "type": "unsigned", size: 4 }`

**Comment by flemmens** [comment]
Thanks ! This way it works 👍
