### ISSUE TITLE
running out of memory during dataset inference

### ISSUE THREAD

**Issue by calvinmetcalf** [connormanning/entwine#33]
I have a bunch of 500MB to 1GB laz files in google cloud storage, I'm treating them like http sources, but when I run entwine on more then 3 or 4 of them at once entwine just dies at the `Performing dataset inference` step, drastically increasing the memory allowed to docker will cause it to work.

So a couple related questions:

- is there a way to pre run the inference stuff?
- am I misreading the documentation and I should just be running it on each image one at a time and merging it into a big pyramid?

**Comment by connormanning** [comment]
The inference should be quite fast/lightweight for LAZ files since it's just a peek at the headers.  For reference I just tested ~40k LAZ files from S3 with 12 threads locally and used under 100MB throughout.  Are these files public?  Can you provide a link to one?

To your questions, yes you can pre-scan the data.  `entwine infer -i my-data/ -o my-data -t 8` will use 8 threads and write a bunch of JSON to `my-data.entwine-inference`.  You can use this file as your build input, e.g. `entwine build -i my-data.entwine-inference -o my-output`.

It doesn't sound like you're doing anything incorrectly - my guess is that for some reason the full files are being downloaded instead of just the starting bytes needed to read the header.

**Comment by calvinmetcalf** [comment]
here is a config that died during inferencing
```json
{
"output": "./entwine/bexar",
"input": [
  "https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998104c.laz",
  "https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998104d.laz",
  "https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998113a.laz",
  "https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998113b.laz",
  "https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998113c.laz",
  "https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998113d.laz",
  "https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998114a.laz",
  "https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998114b.laz",
  "https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998114c.laz",
  "https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998114d.laz",
  "https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998123a.laz",
  "https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998123b.laz",
  "https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998123c.laz",
  "https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998123d.laz"]
}

```

**Comment by connormanning** [comment]
Scanning that dataset takes about 1.5 seconds and under 50MB memory for me.  Can you try the `infer` command I used [here](https://gist.github.com/connormanning/3e85a30c6e4744053174d0c59ca69dc6) to isolate that step?  Please use current master - I've also just pushed a new docker image so re-pull the latest if you're on docker.

When I run `entwine build bexar.json` with your config, I see output similar to that gist for the scanning step, and then the build phase starts almost immediately.  So at this point I have not reproduced what you are seeing.

**Comment by calvinmetcalf** [comment]
running it now, it's definitely taking longer then 1.5 seconds, is maybe docker the issue is there a way for me to build it locally ?

**Comment by connormanning** [comment]
Personally I'd stick with Docker but if you have OSX/homebrew you could follow [this](https://gist.github.com/connormanning/c2c9b5e8f56b1e8d524b8717e33729bd) to build natively.

[Here](https://gist.githubusercontent.com/connormanning/a65f99094c6edd5c38bec1d3cb55a913/raw/c446a60ee9967c218b2e20643f87ac2a082ccf82/docker-infer.sh) is my output using Docker.  Can you post your output?  What is it stuck at?

**Comment by calvinmetcalf** [comment]
[here is my output](https://gist.github.com/calvinmetcalf/81f9508109882f2d5453f08eadfadda8), it hung around lines 12 and 13

**Comment by connormanning** [comment]
I've hounded a couple people to try the `infer` with Docker and got similar results to mine - all on OSX though.  What is your OS and Docker version?

**Comment by calvinmetcalf** [comment]
docker: 17.03.1-ce-mac5 (16048)

mac: 10.12.4

**Comment by connormanning** [comment]
Versions seem fine - my docker version is ` Version: 17.03.1-ce` and OSX is at 10.11.6.  Maybe restart your docker service?

Can you then re-pull the docker image, then add `-v` to your infer command.  Just try one file for now, and remove your volume mapping in case docker is doing anything weird there (although I doubt it).

You should see some curl logging for a GET request including a `Range` header - mine looks like [this](https://gist.githubusercontent.com/connormanning/b3660f6698704fe7f27d214576e0f4e2/raw/832f0564e6b3a8fb7c58fcc96560284e590e1527/verbose-infer.txt).

**Comment by calvinmetcalf** [comment]
```bash
1 / 1: https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998104c.laz
*   Trying 74.125.21.128...
* Connected to storage.googleapis.com (74.125.21.128) port 80 (#0)
> GET /stratmap10_50cm_bexar/stratmap10-50cm_2998104c.laz HTTP/1.1
Host: storage.googleapis.com
Accept: */*
Range: bytes=0-16384

< HTTP/1.1 200 OK
< X-GUploader-UploadID: AEnB2UqnbnqL88xyA2Xp7wP7wlxIlCD7ENZfgaoA08wgJ7PXrHgz-6iEnz8dTLOUdHBBQLbRAXozpRmXIgYEtUWV4rURk_O9lQ
< Expires: Fri, 07 Apr 2017 18:49:50 GMT
< Date: Fri, 07 Apr 2017 17:49:50 GMT
< Cache-Control: public, max-age=3600
< Last-Modified: Wed, 08 Mar 2017 20:58:26 GMT
< ETag: "e046c83f8cdc902b7d925b87deaed19e"
< x-goog-generation: 1489006706724157
< x-goog-metageneration: 2
< x-goog-stored-content-encoding: identity
< x-goog-stored-content-length: 595466309
< Content-Type: application/octet-stream
< Content-Language: en
< x-goog-hash: crc32c=HHInpA==
< x-goog-hash: md5=4EbIP4zckCt9kluH3q7Rng==
< x-goog-storage-class: MULTI_REGIONAL
< Content-Length: 595466309
< Server: UploadServer
< Keep-Alive: 60
< Via: HTTP/1.1 proxy10205
```

**Comment by connormanning** [comment]
Ok that's definitely the problem.  It seems to be ignoring the `Range` header for you.  So when you scan the dataset, you are downloading all ~10GB of your files instead of just the first few thousand bytes of each file.  I have no idea why that is - the HTTP requests look identical to me but the responses are obviously very different.

I'll do some investigation but I currently have no explanation.

**Comment by connormanning** [comment]
Are you behind a proxy?  One that may be stripping off the range headers?

**Comment by calvinmetcalf** [comment]
um let me see if my corporate network is doing something wonky, thank you
for your help

**Comment by calvinmetcalf** [comment]
ok it gets weirder, range requests from curl on the command line do work fine, so at this point I'm going to head home and take a fresh look on monday.  thanks for all your help

**Comment by calvinmetcalf** [comment]
- entwine running curl inside docker downloading from google cloud: range does not work
- running curl from the commandline to download from google cloud: range works fine
- entwine running curl inside docker downloading from local server: range works

I feel like a crazy person but am pretty sure your library is not the issue

**Comment by connormanning** [comment]
You mentioned that curl requests from the command line work as expected - what does the verbose output from one of those look like?

**Comment by calvinmetcalf** [comment]
So there is a difference, doing it from the command line does it via https, but entwine does not, otherwise they seem to be the same

```bash
 curl -r 0-16384 -v https://storage.googleapis.com/stratmap10_50cm_bexar/stratmap10-50cm_2998123d.laz
*   Trying 216.58.217.240...
* TCP_NODELAY set
* Connected to storage.googleapis.com (216.58.217.240) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.storage.googleapis.com
* Server certificate: Google Internet Authority G2
* Server certificate: GeoTrust Global CA
> GET /stratmap10_50cm_bexar/stratmap10-50cm_2998123d.laz HTTP/1.1
> Host: storage.googleapis.com
> Range: bytes=0-16384
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 206 Partial Content
< X-GUploader-UploadID: AEnB2Uod5rbzMGMnowFj6I6N8nbegwvTdtKhrfOtZYuF8S2i-pwAh0QZsM1B70sYxqZrgz4rCH9jHtqkLqcpX468ACx9DdBJ5Q
< Expires: Mon, 10 Apr 2017 18:17:58 GMT
< Date: Mon, 10 Apr 2017 17:17:58 GMT
< Cache-Control: public, max-age=3600
< Last-Modified: Thu, 09 Mar 2017 00:03:44 GMT
< ETag: "4fa1305afc44c2bd163ee2c639b922eb"
< x-goog-generation: 1489017824718126
< x-goog-metageneration: 2
< x-goog-stored-content-encoding: identity
< x-goog-stored-content-length: 673623254
< Content-Type: application/octet-stream
< Content-Language: en
< x-goog-hash: crc32c=lX6pTQ==
< x-goog-hash: md5=T6EwWvxEwr0WPuLGObki6w==
< x-goog-storage-class: MULTI_REGIONAL
< Accept-Ranges: bytes
< Content-Range: bytes 0-16384/673623254
< Content-Length: 16385
< Server: UploadServer
< Alt-Svc: quic=":443"; ma=2592000; v="37,36,35"
```

**Comment by connormanning** [comment]
Nice catch - I've pushed a possible fix.  Can you re-pull the docker image and try once more?

**Comment by calvinmetcalf** [comment]
fixed!

**Comment by connormanning** [comment]
Great.  Thanks for putting up with the remote-debugging session.  Unfortunately your scenario will still be pretty inefficient during the build phase.  We should really be streaming the data to create the required local copies of the input files, but it hasn't been much of an issue yet.  It will be for you though, due to the large and remotely-located input files.

I'd expect to see high memory usage and slow index times for your scenario.  I've created connormanning/arbiter#12 to switch to a streaming interface.  With the current stuff you might be better off downloading those files and indexing them locally.
