### ISSUE TITLE
no driver for s3

### ISSUE THREAD

**Issue by calvinmetcalf** [connormanning/entwine#34]
looking at the docs, I should be able to run 

```bash
docker run -it  -v `pwd`:`pwd` -w `pwd` --rm connormanning/entwine build -i s3://iowa-lidar/iowa/ -o ./some/directory
```

but doing so and I get the error `Encountered an error: No driver for s3://iowa-lidar/iowa/*`

**Comment by connormanning** [comment]
You need to specify credentials for S3 to work.  In general you want to link your volume AWS config directory `-v ~/.aws:/root/.aws`, but you could also use explicit environment settings.

**Comment by calvinmetcalf** [comment]
ok reading the docs looked like i should be able to also put

```json
"arbiter":{
  "s3":{
    "endpoint": "storage.googleapis.com",
    "access":"access",
    "secret":"secret"
  }
}

in the config, but is that not the case?
```

**Comment by connormanning** [comment]
Can you go back a step, where is this JSON residing?  When you say "in the config" do you mean in `~/.aws/config`?

**Comment by connormanning** [comment]
Oops, looks like there was a half-done change there so it wasn't picking up that config portion.  Fixed and pushed, please repull and retry.

**Comment by calvinmetcalf** [comment]
ah thanks!

**Comment by calvinmetcalf** [comment]
sigh, the cloud storage interoperability thing only supports an older version of the api, the one using sha1 instead of sha256

**Comment by pogilon** [comment]
@connormanning  is this working for the docker already? I am having the similar error using the docker.

**Comment by pogilon** [comment]
Dear Connor,

I am trying to index some point clouds into S3 using the command:

sudo docker run -it -v $HOME:$HOME --rm connormanning/entwine build \
    -i https://entwine.io/sample-data/red-rocks.laz \
    -o s3://pointclouds.server/pc

resulting in an error: "no driver for s3"

Then I tried:

sudo docker run -it -v ~/.aws:/root/.aws --rm connormanning/entwine build \
    -i https://entwine.io/sample-data/red-rocks.laz \
    -o s3://pointclouds.server/pc

but got a different error:

Found an SRS
	Failed PUT attempt 1: 1398101.laz
	Failed PUT attempt 1: 611669.laz
	Failed PUT attempt 1: 873813.laz
	Failed PUT attempt 2: 1398101.laz
	Failed PUT attempt 1: 349525.laz
	Failed PUT attempt 1: 1135957.laz
	Failed PUT attempt 2: 611669.laz
	Failed PUT attempt 3: 1398101.laz
	Failed PUT attempt 2: 873813.laz
	.....

Do you have more detailed recommendations about how to index point clouds in amazon S3? Thanks

**Comment by connormanning** [comment]
Your volume mapping looks fine.  My guess is that whatever credentials you've mapped don't have write permissions to that bucket.  Are you able to write to that bucket with awscli?

**Comment by pogilon** [comment]
@connormanning . Yes, I just wrote a file to the bucket using awscli "cp" command. The user key only has permission to read/write in that bucket. What other permissions should the user key have in order to work? Thanks!

**Comment by pogilon** [comment]
@connormanning  that user key has "AmazonS3FullAccess", but no luck

**Comment by connormanning** [comment]
Try setting the `CURL_VERBOSE` environment var in your docker command, i.e. `docker run -it -e "CURL_VERBOSE=1"` connormanning/entwine build ...`.  It'll likely flood your console, but you might be able to pick out what the issue is from the HTTP traffic.

**Comment by pogilon** [comment]
@connormanning  Thank you. I solved by. The aws configure  command needed to contain the region where the bucket was located too. Thanks.
