### ISSUE TITLE
Text input files

### ISSUE THREAD

**Issue by mikeskaug** [connormanning/entwine#35]
I've been trying to index some data, with the eventual goal of serving it with Greyhound, but so far I've failed to get the data into a format that Entwine can parse.

Our data is in a pgpointcloud database, but prior to ingest, it was written to csv text files. Somewhere it said that Entwine could parse anything that is PDAL readable, however when I supply the csv directory as input `-i csv/` I get an error: `Encountered an error: No point cloud files found`. Is it possible to use text files as input?

Having failed with text file input, I decided to convert the files to `las` format myself using PDAL. I did that, but when I run the build I get this error: `Cannot use this scale for these bounds`. My guess is that something's wrong with the las files - the min/max values in the header are all zero:
```
"maxx": 0,
"maxy": 0,
"maxz": 0,
"minx": 0,
"miny": 0,
"minz": 0,
"scale_x": 1,
"scale_y": 1,
"scale_z": 1,
```

If you have any thoughts or suggestions, they would be greatly appreciated.

**Comment by connormanning** [comment]
Can you share a sample CSV and/or LAS file that you are trying to index?

**Comment by mikeskaug** [comment]
Here's the start of one of the CSVs:
```
RelativeTime,Latitude,Longitude,Elevation,StartPulse,ReflectedPulse,Azimuth,Pitch,Roll,PDOP,PulseWidth,GPSTime,DateTime
0.0,69.333115,-49.841993,630.1270141601562,2712,3414,128.09100341796875,3.5399999618530273,1.1779999732971191,2.5,19.0,131940.43600000002,526742380.436
0.0,69.333181,-49.84185000000002,630.3690185546875,2481,3187,129.9810028076172,3.5399999618530273,1.1779999732971191,2.5,19.0,131940.43600000002,526742380.436
0.0010000000474974513,69.333245,-49.841702999999995,630.2999877929688,2757,3387,131.8730010986328,3.5399999618530273,1.1779999732971191,2.5,20.0,131940.43600000002,526742380.436
```

Here's a link to the full CSV (~200MB): https://www.dropbox.com/s/n8ukzpnupxomv30/ILATM1B_20130404_133128.ATM4BT4.h5.csv?dl=0

And here is the corresponding las file (~40MB): https://www.dropbox.com/s/aehd2bl73wgogyl/ILATM1B_20130404_133128.ATM4BT4.h5.csv.las?dl=0

**Comment by connormanning** [comment]
Thanks for the sample file.  There are a few things at play here.  One was that PDAL did not have `.csv` mapped to any reader, hence your 'no point cloud files found' error.  I've fixed this in PDAL master, but entwine's dependent docker container hasn't been updated.  If you're using docker, you'll need to rename them to `.txt` for now.

The next issue you'll have is that you don't have XYZ dimensions in your file.  PDAL/Entwine pretty much these to be present - otherwise PDAL translation to other formats won't work and Entwine won't know how to index your data properly.  The easiest thing to do would be to rename `Latitude,Longitude,Elevation` to `X,Y,Z` in your file header for now.

Once you've done that, you'll probably want to reproject to something non-spherical if you want to look at things in a renderer.  For example you could add `-r EPSG:4326 EPSG:3857` during your `entwine build` step.

You'll need to re-pull Entwine as well - I just made some changes/fixes that you'll need.

**Comment by mikeskaug** [comment]
Thanks for looking into this!

I was thinking the same thing about the `.csv` ending, so I tried renaming the files to `.txt`, but I got the same result. Just to make sure, I tried it again and this was the output (using `connormanning/entwine:latest`):
```
Resolving [file]: /Users/misk6091/csv/* ...
	Resolved to 14 paths.
Performing dataset inference...
1 / 14: /Users/misk6091/csv/ILATM1B_20130404_133128.txt
2 / 14: /Users/misk6091/csv/ILATM1B_20130404_134428.txt
3 / 14: /Users/misk6091/csv/ILATM1B_20130410_125505.txt
4 / 14: /Users/misk6091/csv/ILATM1B_20130410_130133.txt
5 / 14: /Users/misk6091/csv/ILATM1B_20140409_133356.txt
6 / 14: /Users/misk6091/csv/ILATM1B_20140409_135337.txt
7 / 14: /Users/misk6091/csv/ILATM1B_20140419_130253.txt
8 / 14: /Users/misk6091/csv/ILATM1B_20140419_132234.txt
9 / 14: /Users/misk6091/csv/ILATM1B_20150421_135359.txt
10 / 14: /Users/misk6091/csv/ILATM1B_20150425_124105.txt
11 / 14: /Users/misk6091/csv/ILATM1B_20150425_132844.txt
12 / 14: /Users/misk6091/csv/ILATM1B_20160906_103940.txt
13 / 14: /Users/misk6091/csv/ILATM1B_20160909_104747.txt
14 / 14: /Users/misk6091/csv/ILATM1B_20160909_131940.txt
Encountered an error: No point cloud files found
Exiting.
```

I was wondering about the dimension names - thanks for the tip. I did notice that when I use PDAL to convert to `.csv` files to `.las`, the output schema has X,Y, and Z:
```
"schema":
  {
    "dimensions":
    [
      {
        "name": "X",
        "size": 8,
        "type": "floating"
      },
      {
        "name": "Y",
        "size": 8,
        "type": "floating"
      },
      {
        "name": "Z",
        "size": 8,
        "type": "floating"
      },
...
```
Based on that, I thought that it was getting converted correctly, but now I realize that none of the other dimensions correspond with anything in the input CSV file, so obviously something's not quite right.

I didn't realize reprojection was necessary, but I guess that makes sense that something non-polar would be needed.

I will re-pull the entwine image and try some of this.

**Comment by mikeskaug** [comment]
Sorry, I hadn't pulled `entwine:latest` when I tried the `.csv` -> `.txt` rename. It works now.
