### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by JSFrias** [connormanning/entwine#36]
Connor, your documentation seems to imply that it's possible to add LiDAR files to already indexed data. So for example I run entwine on 'a.laz' into folder 'MyData'.  Once that's finished I run entwine on 'b.laz' also into folder 'MyData', and entwine quickly comes back with this error:

**sudo docker run -it -v //media/lidar-share/:/data connormanning/entwine build -i /data/b.laz -o /data/MyData
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector<bool>::_M_range_check: __n (which is 1) >= this->size() (which is 1)
Got error 11
terminate called recursively**

I have been experimenting with Entwine solidly for a couple of weeks. I'm aware that I can process these files together with a single command (but here I'm specifically testing the ability to add to an existing index). I've also tried specifying a 'Bounds' (that encompasses both files) while processing 'a.laz', with the same result.

Both laz files are in EPSG:3857, and are geographically close to one another (but perhaps 30 miles apart). 

Any idea what I'm doing wrong?

Thank you in advance.

**Comment by connormanning** [comment]
Sounds like a bug/regression.  I'll take a look now.

**Comment by JSFrias** [comment]
Thank so much. For what it's worth it seems like I was able to make this work two weeks ago (albeit with different files), so I guess, a regression is possible but it doesn't seem like entwine has been updated that recently.

**Comment by connormanning** [comment]
9bf2b98 should fix this issue.  There were also some other issues with continued builds I found and took care of as well - where behavior might have been inconsistent for continued builds (maybe why it worked for you before with different data).  I've pushed a new docker container with these fixes so please re-pull and try again.

**Comment by JSFrias** [comment]
Thank you so much. BTW I tried to divine your Hobu e-mail address and sent you a note. It hasn't bounced. Just wondering if there is any way we could talk on the phone for a few minutes.

**Comment by connormanning** [comment]
Closed via 9bf2b98.
