### ISSUE TITLE
Running out of Memory

### ISSUE THREAD

**Issue by JSFrias** [connormanning/entwine#41]
Connor,

Thank you again for taking my call two weeks ago.  [for the benefit of others] I explained that I had a very large data set that I hope to index with entwine (70,000 + files, 18+ TB compressed, 3.7 trillion points, spanning the entire US).  I've been encouraged by your demonstration https://av.tib.eu/media/20366 of comparable data sets (denser but more confined than mine) in Iowa and the Netherlands.  You advised me to do two things with my set. One, I should break things up into multiple resources, rather attempting to put the entire US into a single resource. And two, that entwine takes better advantage of parallelization when the individual files are broken into smaller pieces that what mine were in at the time. I wrote code to do just that, and decided to break up my set into individual resources along Web Mercator zoom level 6 tile boundaries (which for reference are just a little larger than the state of Iowa). My code also breaks my source files into smaller pieces (along WM zoom level 16 boundaries), ranging in size from 1k (containing a single point) to 81Mb (15,317,899 points), and averaging somewhere in the 30Mb range.  At the moment I'm focused on processing my most modest "tile" pictured here at zoom 6 and zoom 8:

![indexmap](https://cloud.githubusercontent.com/assets/17951316/26316646/cc78aa56-3ec9-11e7-9260-7db5bc61f645.png)

This set consist of 3714 laz files at 27.8 GB.  I am not currently imposing the tile boundary (by defining the bounds with the Entwine '-b' parameter) though that is my hope in the future so that I can add data to some of these resources if needed. This resource is quite modest in comparison to those you have demoed. The data itself is not overly dense or unusual.

The problem is that I keep running out of memory every time I try to index this set. I am running this on a single Ubuntu Box (though I have four at my disposal) inside of docker. The box has 60GB of ram and 30 cores.  I've tried running the job as subsets all the way to 64 pieces but the result is always the same. Things seem to start out running at a decent clip, but eventually slow as the entire 60GB of physical ram and then the 25GB page file is completely consumed. I'm processing this all on my local network.

The command I'm using is this:

sudo docker run -it -v /media/lidar-share/data connormanning/entwine build -i /data/source_split/MyData/9_39 -o /data/MyData/9_39 -t 30

I have not played with the nullDepth or baseDepth parameters, but I do need this to be lossless.

Do you have any other suggestions? Your help is much appreciated. I've got some time to complete processing on the whole of my job, but I'm getting a little pressure to be able to provide a demo on at least this small portion.

Thanks again for you help and excellent work,

-John

**Comment by connormanning** [comment]
Can you post the initial summary portion of the log?  The part with `Input` `Output` and `Metadata`  etc.

If there is any way you could make this data available to me I could debug the build myself.  From everything you've said, there is nothing that stands out to me which would cause these issues.

**Comment by hobu** [comment]
> The problem is that I keep running out of memory every time I try to index this set.

Is there a chance the issue is just docker falling over and running out of memory? Or does it appear something is growing unconstrained?

**Comment by JSFrias** [comment]
It was also my sense was that something was growing unconstrained, but I think I have found my problem and it is my own. My laz headers are corrupted (so nice intuition Harold). I apologize. I was pulling my hair out all weekend trying different things, and NOT looking at my headers; I rushed in this morning to ask for your help (I'm on the west coast). I just turned my headers into a shape file, and they are WAY off. I'm sure things will be fine once I fix this. I'll report back later today if you want to keep this open until then. Thanks again, both of you. (P.S. Harold, if I didn't make it clear at the end of our call, once this is all said and done, I 'll provide you with screen shots, video, or whatever I can for you to use in your marketing)

**Comment by JSFrias** [comment]
I have my headers fixed. I'm re-running this set. I will let you know one way or another in a few hours. Thanks again for your help.

**Comment by connormanning** [comment]
To add some documentation to this ticket since @JSFrias and I went offline for this - the issue was caused due to the very narrow footprint of the data in comparison with the overall bounds.  Entwine's estimation of the data density, which is very crude but works for typical tiled data, was very far off for this data.  Thus, the chunking of the tree was very poorly optimized by default for this data.

I was able to trick Entwine by altering the `numPointsHint` field, but the real fix would be to gather a better density estimation during the pre-build header-scanning phase.  I've opened #48 to address this enhancement.

**Comment by julienlau** [comment]
I now this was a long time ago, but I found the issue interesting since I am considering using a large covering area for an EPT that would be very sparsely filled.

Do you consider it a good idea or is it more recommended to have approximately uniform point density across the EPT bbox ?
@connormanning
