### ISSUE TITLE
greyhound and s3

### ISSUE THREAD

**Issue by aleksandrmelnyk** [connormanning/entwine#42]
Hi there,

does anybody know how to connect greyhound to s3, so that it serves index created on s3?

thanks,

Alex.

**Comment by connormanning** [comment]
If you have your S3 credentials in `~/.aws/`, then you'll need to link that directory into docker: `-v ~/.aws:/root/.aws`.  Details [here](https://github.com/connormanning/entwine/blob/master/doc/usage/configuration.md#s3).

Then, you'll need to add your S3 bucket in the `paths` portion of the configuration - details [here](https://github.com/hobu/greyhound/blob/master/doc/administration.rst#configuration).  For example, `paths: ["s3://my-bucket"]`.

**Comment by aleksandrmelnyk** [comment]
Connormanning, thanks much that helped. I have successfully started the server. in case someone else needs quick commans for this, here it is (assuming greyhouns conf is in /usr/local/projects/entwine):

> docker run -it -v ~/.aws:/root/.aws -v /usr/local/projects/entwine:/opt/data -p 8181:8181 connormanning/greyhound -c /opt/data/greyhound.conf

But are there any instructions on how to connect a client to this server, say potree.js? How the client will recognise its interface?

thanks,

Alex.

**Comment by connormanning** [comment]
The [Greyhound readme](https://github.com/hobu/greyhound#viewing-the-data) has some info on this - the links at the end of that section give some information on accessing your data with our public Potree demo.  For example, if your output is stored at `s3://my-bucket/chicago`, you could access your index with http://potree.entwine.io/data/custom.html?s=localhost:8181&r=chicago.

For using potree.js directly in your own website, you can take a look at the repository [connormanning/potree.entwine.io](https://github.com/connormanning/potree.entwine.io) as a basis for scripting Potree to interact Greyhound.

**Comment by aleksandrmelnyk** [comment]
Thanks much!
