### ISSUE TITLE
Exception in pool task: Unable to fetch data and convert as requested: Blue:uint16_t(31232) -> unsigned char

### ISSUE THREAD

**Issue by aleksandrmelnyk** [connormanning/entwine#43]
Hi,

am trying to build index for cesium 3d tiles with following command:

> docker run -it -v h:/:/opt/data connormanning/entwine build /opt/data/arrow_laz_index/cesium.json -i /opt/data/arrow_laz/e3085n69655.laz -o /opt/data/arrow_laz_index/data

```
{
   "absolute":true,
   "reprojection":{
      "out":"EPSG:4326"
   },
   "formats":{
      "cesium":{
         "tilesetSplit":8,
         "geometricErrorDivisor":16.0
      }
   }
}
```

on windows 10.
In the output directory only empty folder are created, and powershell output is full of those 'Unable to fetch data and convert as requested' entries.
![2017-05-24_0948](https://cloud.githubusercontent.com/assets/930971/26390808/cf6e8136-4068-11e7-8176-e765ed261108.png)

Also in the output it says it gonna convert into 4978, but in cesium.conf 4326 is set, may be it is related.
any ideas what could it be?

thanks,

Alex.

**Comment by connormanning** [comment]
This is the same issue as #26 - your color values are 16-bit (which is fine, normally) but Cesium 3d-tiles format only allows 8-bit.  You'll need to normalize them before indexing.

As for 4978 vs 4326, if cesium output is enabled, 4978 will be forced regardless of any other settings in the configuration.

**Comment by aleksandrmelnyk** [comment]
Thanks, gonna try to fix that.
