### ISSUE TITLE
entwine infer bounding box

### ISSUE THREAD

**Issue by adamsteer** [connormanning/entwine#45]
When I run 'entwine infer ...' over a directory of files it returns a bounding box which captures the extent of all data in that directory. If I add '-r EPSG:native EPSG:desired', the bounding box returned by infer seems to be correct in the EPSG:desired system.

I then set up a bash script to add one LAZ tile at a time to an entwine build, using the bounding box for the whole dataset, in the EPSG:desired CRS:

for file in dir:
entwine build -i file -o output_dir -r EPSG:native EPSG:desired -h -b [min, max xyz of desired CRS] -x -t (Nphysicalcores-2)

I know this will take time due to the -x option, but after the first tile is inserted entwine returns '0 points inserted, Npoints out of bounding box'. This seems strange, since the bounding box provided *should* capture all the data in the directory. Is that how the -b option is meant to work? or am I messing with things by using -x as well?

**Comment by connormanning** [comment]
Your description sounds solid enough, so this sounds like a bug to me.  I'll try to reproduce and make a fix.  The procedure does sound a bit strange though.

- Why add files one at a time?  Why not just `entwine build -i all-my-stuff/ -o ...`
- Why the `-x` option?  Are your headers known to be inaccurate?

**Comment by adamsteer** [comment]
`entwine build -i all-my-stuff/ -o ...` always gets killed after 5 or so tiles are added (out of 818), even winding back the number of threads a lot (to -t 2 ).

**Comment by adamsteer** [comment]
closing- Connor explained that inferring cesium bounding boxes might not work as I thought. This appears to be a user-keyboard interface issue not an entwine issue.
