### ISSUE TITLE
Building multiple source files

### ISSUE THREAD

**Issue by aleksandrmelnyk** [connormanning/entwine#46]
Hi,

am trying to build 3d-tiles from many source laz files, but entwine stops adding/build source after 4rth file, and command just stops without showing any error. Could it be due to that fact that source laz file are disjount, eg they are not close to each other and make different parts of surface?
![2017-05-28_0821](https://cloud.githubusercontent.com/assets/930971/26526302/b0a3b05a-437e-11e7-9a1c-c155a691ac3f.png)

![2017-05-28_0819](https://cloud.githubusercontent.com/assets/930971/26526294/8695938c-437e-11e7-9f7a-c4a77d339655.png)

thanks,

Alex.

**Comment by connormanning** [comment]
Can you provide access to some of the data?  I haven't seen this problem occur before, and I'm not sure what might cause it.

**Comment by aleksandrmelnyk** [comment]
I have extracted 5 initial laz files to reproduce issue with them, put them into seperate folder on s3, but now seems it shows some issue, seems like it also trying to read folder itself, attached:
![2017-05-29_0749](https://cloud.githubusercontent.com/assets/930971/26536859/795bb956-4443-11e7-89b7-9b9bbfdac8f7.png)

![2017-05-29_0750](https://cloud.githubusercontent.com/assets/930971/26536862/8024abe4-4443-11e7-811f-fc547b74fd92.png)

**Comment by aleksandrmelnyk** [comment]
Actually when I specify multiple files in json configuration it also fails but shows std:alloc, attached.
![2017-05-29_1636](https://cloud.githubusercontent.com/assets/930971/26551892/62c70570-448d-11e7-9d74-8b616203142a.png)

**Comment by connormanning** [comment]
Can you email me an S3 key with read access to that bucket?  Or upload them somewhere public.  Without your data I can't really investigate.

**Comment by aleksandrmelnyk** [comment]
Hi Connormanning, 

sorry, i cannot share access to this data, it is out of my competency. Only can say that for potree format the index is generated just fine from the laz files. 
May be let's w8 while the issue can be reproduced on some other (not restricted) dataset.

thanks,

Alex.

**Comment by connormanning** [comment]
You mentioned earlier: `laz file are disjount, eg they are not close to each other and make different parts of surface`.  That could potentially be the problem.  I would recommend isolating files from each part of the surface and indexing them separately.  With Cesium, you could then simply add each individual tileset to the viewer and things would work just fine.

You can isolate the bounds of each of your 1109 files by running `entwine infer s3://keys/arrow_sample_laz/3d-tiles/10781/ -o 10781`, which would create a file called `10781.entwine-inference`.  This file contains a JSON array called `fileInfo` with metadata for each files, and you could potentially parse it and do some scripting based on the `bounds` there to figure out which files should be grouped together.

Feel free to reopen this issue if you are ever able to reproduce it with data that is shareable with me.

**Comment by aleksandrmelnyk** [comment]
Thanks much, I'll try that.

**Comment by aleksandrmelnyk** [comment]
btw, have successfully built multiple laz files which are neighboring/adjacent. Will see how it work on bigger dataset.
