### ISSUE TITLE
3d-tiles layer height

### ISSUE THREAD

**Issue by aleksandrmelnyk** [connormanning/entwine#47]

**Comment by aleksandrmelnyk** [comment]
tiles generated with the entwine tool, when rendering are shown higher than base layer of cesium. Any ideas how to place them just on top of base layer?

**Comment by connormanning** [comment]
See #28 and connormanning/entwine-cesium-pages#5.  Are you using the ellipsoid or the terrain meshes as your base layer?  It's likely that one of those layers matches properly - it depends on the vertical datum of your input data.
