### ISSUE TITLE
Entwine not reading points

### ISSUE THREAD

**Issue by psawall** [connormanning/entwine#49]
Whenever I try to run Entwine in docker, I keep getting the same error, regardless of the data set used.

>$ docker run -it -v $HOME:$HOME connormanning/entwine build \
>     -i /C/Users/psawall/entwine/Input/i35_MN_LiDAR_Colored.laz \
>     -o ~/entwine/Output/i35_MN_LiDAR_Colored
>Performing dataset inference...
>1 / 1: /C/Users/psawall/entwine/Input/i35_MN_LiDAR_Colored.laz
>Exception in pool task: Unable to open stream for >'/C/Users/psawall/entwine/Input/i35_MN_LiDAR_Colored.laz' with error 'No such file or directory'
>Cannot use this scale for these bounds
>Encountered an error: Zero points found
>Exiting.

**Comment by connormanning** [comment]
This is a volume mapping issue.  Take a look [here](https://github.com/connormanning/entwine-cesium-pages/issues/6#issuecomment-301779026).

**Comment by rromanchuk** [comment]
@psawall not sure how i ended up here but now I want that i35 lidar haha. Is that from a specific MNDNR collection or your own point cloud?

**Comment by psawall** [comment]
@rromanchuk It was LiDAR from MNDNR that I colored with an orthophoto. I don't still have the dataset.
