### ISSUE TITLE
S3 driver: following provider-chain and picking up credentials via IAM role?

### ISSUE THREAD

**Issue by jfinken** [connormanning/entwine#50]
Hi Connor,

Next question for you.  Similar to issue #34 I am receiving `Encountered an error: No driver for s3://<bucket>/<prefix>/*`

I suspect the difference between issue #34 and my scenario is that I am running `entwine build` on EC2 not on an on-premises machine, thus explicit AWS keys will never be provided.  It is expected that the application will follow the default credential provider chain and, in my case, be granted access to the bucket via an IAM role under which the EC2 instance is running.

For example, on EC2 this just works:

    sudo docker run garland/aws-cli-docker aws s3 ls

Is entwine expecting explicit AWS access keys as per the [doc for the S3 backend](https://github.com/connormanning/entwine/blob/master/doc/usage/configuration.md#s3)?

Many thanks in advance.

**Comment by connormanning** [comment]
Pull the latest docker image, and then try adding `-e AWS_ALLOW_INSTANCE_PROFILE=1` to your docker invocation.

**Comment by jfinken** [comment]
You are fast, that works.  Thank you!
