### ISSUE TITLE
Protocol "s3" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by pogilon** [connormanning/entwine#51]
Hello, I am trying to index a local point cloud directly into an S3 bucket. However, I am getting a failed PUT attempt (see command at the end). When running with "curl_verbose=1", I get:

Protocol "s3" not supported or disabled in libcurl

Any ideas on how to solve this? Thanks!

sudo docker run -it -v ~/.aws:/root/.aws -e "CURL_VERBOSE=1" -v $HOME:$HOME connormanning/entwine build \
    -i /path/to/point/cloud \
    -o s3://path/to/bucket/folder

**Comment by connormanning** [comment]
I updated the IO package used by Entwine the other day - looks like a bug was introduced in the S3 driver.  I'll take a look.

**Comment by connormanning** [comment]
A fix has been pushed and the docker image is updated.

**Comment by pogilon** [comment]
@connormanning great! very fast fix! incredible!
