### ISSUE TITLE
Is text based tree hierarchy information able to be generated from entwine?

### ISSUE THREAD

**Issue by ryanuc** [connormanning/entwine#52]
Is it possible to generate some form of text based hierarchy information about the entwine laz outputs?  In my testing I'm successfully generating plenty of .LAZ files and they're clearly split into a great tree structure, however I'd really like to gather information on the relationships between the different files to perform some further processing via some python scripts I'm creating.  Ideally I'd like the parent/child relationships between each file.  The generated .json files (eg entwine-manifest) does not appear to contain this information.  I'm guessing it perhaps lives in the 0 file in the h (hierarchy?) folder, however it is binary so it is largely not usable to me at this stage.  Likewise, I can't see any options in the documentation for generating information like this.  Of course I could delve into the source code and see if there is something I can expose, however I thought I'd check here first as others may have solved this.

**Comment by connormanning** [comment]
The file you're referring to is LZMA compressed (but even uncompressed, it's still a binary format) that contains information about the number of points in various cubes.  It doesn't map directly to the on-disk file structure.

I've made a small C++ app that can give you a JSON representation of the file hierarchy structure.  Pull the latest docker image and give this a try: https://gist.github.com/connormanning/1d63e4a0a1f8dbc9ebfe2c46d782d0f6

**Comment by ryanuc** [comment]
Great thanks, this does exactly what I need!
