### ISSUE TITLE
entwine build appears to ignore threads directive

### ISSUE THREAD

**Issue by adamsteer** [connormanning/entwine#53]
if I say 'entwine build -i ... -o ... -t 2', entwine says:

Transforming inference
Inferred: [(-8497.0259, -18951.106, -4258.3861), (9192.7131, 16498.431, 643.58951)]

Version: 1.1.0
Input:
	Files: 79
	Point count hint: 4,793,770,294 points
	Threads: 5
Output:

The same happens if my json config file says "threads": 2 

Why am I trying to limit the number of threads? I'm happy for my build to take a while, but I am a little memory-constrained. Related to this, entwine seems to consume a lot of memory - is it trying to hold the entire dataset in memory at once? Or for 4.7 bill points should I be doing subset builds? or should I just stump up for more RAM ;) Sorry, more than one question per issue there...

**Comment by adamsteer** [comment]
Winding back my entwine build to 1.0.0 seems to have fixed my memory issues, but I'm still not certain about how entwine's picture of threads in use matches the threads directive provided in the command line.

**Comment by connormanning** [comment]
Entwine has two types of threads - worker threads that read files and insert data, and serialization threads that do the I/O for indexed data chunks when they haven't been used in a while.  If you request fewer than 5 threads, you'll get one worker thread and four serialization threads - which explains what you're seeing.

For your case specifically, although not mentioned in this ticket I know you're using the Cesium config, and the issue you're seeing seems to be a bug in the Cesium code which I haven't yet tracked down.  In general, the memory usage of Entwine is driven by the number of threads, and should be relatively constant after a while no matter how many points are inserted.

There's probably a leak in the Cesium code at the moment, so for now using 1.0 is good advice - and will help me track down the issue 👍
