### ISSUE TITLE
Errors!

### ISSUE THREAD

**Issue by pogilon** [connormanning/entwine#54]
Hello @connormanning. Could you please help us resolve this new issue?

Now when running the example code:

sudo docker run -it -v $HOME:$HOME -e "CURL_VERBOSE=1" connormanning/entwine build \
    -i https://entwine.io/sample-data/red-rocks.laz \
    -o ~/entwine/red-rocks
I get the error:

------------------------------------------------------
Curl config:
	timeout: 5s
	followRedirect: true
	verifyPeer: true
	caBundle: (default)
	caInfo: (default)
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1889424) >= this->size() (which is 1889424)
Got error 11
terminate called recursively
-----------------------------------------------------------

and when running it locally:

sudo docker run -it -v $HOME:$HOME -e "CURL_VERBOSE=1"  connormanning/entwine build \ 
	-i $HOME/red-rocks.laz \ 
	-o ~/greyhound/red-rocks
I get:
----------------------------------------------------
timeout: 5s
	followRedirect: true
	verifyPeer: true
	caBundle: (default)
	caInfo: (default)
Encountered an error: Could not read file  
Exiting.
-----------------------------------------------

**Comment by connormanning** [comment]
Sounds like you have a pre-1.0 index there already.  Try adding the `-f` flag, or deleting your output directory before building.

**Comment by pogilon** [comment]
@connormanning  Thank you. You were right. Please close
