### ISSUE TITLE
logic_error thrown without absolute flag is set

### ISSUE THREAD

**Issue by LHolst** [connormanning/entwine#56]
I run entwine build with the cesium config inside docker and got this error:
``` bash
Got error 11
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```
with data from [http://geoportal.geoportal-th.de/hoehendaten/LAS/las_2014-2019/las_658_5654_1_th_2014-2019.zip](http://geoportal.geoportal-th.de/hoehendaten/LAS/las_2014-2019/las_658_5654_1_th_2014-2019.zip)

i rebuild the docker image and found that in da88b83768c94ebf597ac7a1313e28ed6e9a9e3d the **absolute** setting was removed from the cesium config. At that commit the image worked.

when setting the **absolute** flag, the process completed too
`entwine build /var/entwine/config/cesium.json -i las_658_5654_1_th_2014-2019.laz -o cs_local -r EPSG:25832 EPSG:4978 -n`

**Comment by connormanning** [comment]
Thanks for providing the data - I've reproduced your issue and will look into the cause.

**Comment by connormanning** [comment]
This should be fixed, and I've just pushed an updated docker image.

**Comment by LHolst** [comment]
Great, latest docker image from dockerhub works .
