### ISSUE TITLE
basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by pogilon** [connormanning/entwine#57]
Hello @connormanning . I run into this error when trying to index a point cloud using entwine. It only happens for a specific point cloud. What could it be? This only indexes a portion of the total points in the point cloud. Thanks!
"
Found an SRS
Got error 11
Exception in pool task: basic_string::_M_construct null not valid
During /media/smarty/Storage/Dropbox/NBM_Projects/Project_Rail_0000001/pointclouds/klk.las: Subtraction result was negative (block zero)
Saving hierarchy...
Saving registry...
Saving metadata...

Index completed in 66 seconds.
Save complete.  Indexing stats:
	Points inserted: 19,537,920
	Points discarded:
		Outside specified bounds: 0
		Overflow past max depth: 0
"

**Comment by connormanning** [comment]
Not sure.  I recently fixed an issue that could have caused an error similar to this.  Update your docker image (or git pull if native) and re-run with `-f` to force over the previous build.  If that doesn't help, you could email me the file and I'll take a look.

**Comment by connormanning** [comment]
Closing, re-open if necessary with the current codebase.
