### ISSUE TITLE
Less points inserted

### ISSUE THREAD

**Issue by kunallanjewar** [connormanning/entwine#58]
Hello again @connormanning 
I'm running entwine for a newer dataset, however, it's not inserting all the points.
I have attached the dataset here.
[AIRS.zip](https://github.com/connormanning/entwine/files/1174964/AIRS.zip)

### This is command I used.
 ```
docker run -it \
    -v $HOME:$HOME \
    connormanning/entwine \
    build \
        -f \
        -i AIRS.las \
        -o ~/entwine/airs-default/ \
        -r EPSG:4326 EPSG:4978

```
### Here is output I'm getting

```
Performing dataset inference...
1 / 1: AIRS.las
Inferred: [(-90, -180, 0), (89, 179, 23)]

Version: 1.1.0
Input:
        File: AIRS.las
        Point count hint: 1,555,200 points
        Density estimate (per square unit): 24.2013
        Threads: 8
Output:
        Output path: AIRS/

        Data storage: laszip
        Scale: 0.01
        Offset: (10, 10, 20)
        XYZ width: 4
Metadata:
        Native bounds: [(-90, -180, 0), (89, 179, 23)]
        Cubic bounds: [(-200, -200, -190), (220, 220, 230)]
        Reprojection: (from file headers, or a default of 'EPSG:4326') -> EPSG:4978
        Storing dimensions: [
                X, Y, Z, Intensity, ReturnNumber
                NumberOfReturns, ScanDirectionFlag, EdgeOfFlightLine, Classification, ScanAngleRank
                UserData, PointSourceId, GpsTime, Red, Green
                Blue, OriginId
        ]

Adding 0 - ~/entwine/airs-default/
        Pushes complete - joining...
Saving hierarchy...
Saving registry...
Saving metadata...


Index completed in 3 seconds.
Save complete.  Indexing stats:
        Points inserted: 756,045
        Points discarded:
                Outside specified bounds: 781,920
                Overflow past max depth: 0

Process Completed.

```
Here is how it looks like in MeshLab
<img width="897" alt="screen shot 2017-07-25 at 4 00 04 pm" src="https://user-images.githubusercontent.com/5488221/28597388-5caad062-7152-11e7-8a5f-5776178fb71a.png">

Any idea why is it doing that? Thanks!

**Comment by connormanning** [comment]
Try running with the `-x` flag.  Looks like an issue with the way that the reprojected bounds are being calculated from the header, so using `-x` should solve this for now until I determine the reason for the issue.

**Comment by kunallanjewar** [comment]
Hi 

I tried -x flag and here is my result in potree. I did insert all the points this time.
The data is suppose to wrap around the whole globe but as you can see it's half dome. Also it is not reprojected properly. 

**Top View:**
<img width="856" alt="screen shot 2017-07-26 at 11 47 13 am" src="https://user-images.githubusercontent.com/5488221/28638106-abc78db0-71f8-11e7-8cc3-551398a53b02.png">

**Side View**
<img width="740" alt="screen shot 2017-07-26 at 11 47 27 am" src="https://user-images.githubusercontent.com/5488221/28638137-cb759166-71f8-11e7-9b9e-5bac62999bea.png">

**Comment by connormanning** [comment]
Looks like your latitudes/longitudes were switched.  I swapped them with filters.programmable:

```
import numpy as np
def swap_xy(a, b):
    v = a['X']
    b['X'] = a['Y']
    b['Y'] = v;
    return True
```

<img width="503" alt="potree" src="https://user-images.githubusercontent.com/5015470/28900434-c4945f4e-77b6-11e7-84f5-d46de58fbc07.png">

[airs-swapped.las.zip](https://github.com/connormanning/entwine/files/1195597/airs-swapped.las.zip)

Looks better, but I think you might look into stretching out your Z-values so all the Z's aren't stacked together.  You end up with a lot of twinkling in potree with all the near-identical points for each X/Y - you could add a single line into that filter to do so.

Entwine is pretty poorly optimized for this sort of data, so allow it some extra time to index..
