### ISSUE TITLE
Cesium per-point data

### ISSUE THREAD

**Issue by LHolst** [connormanning/entwine#59]
How hard would it be get meta data into the cesium format? I would like to have per-point data written to the BatchTable inside the pnts files. Data could be `height` or `Z` value before the reprojection to "EPSG:4978".

[PointCloud#batch-table ](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/TileFormats/PointCloud#batch-table) says its possible without introducing `BatchID` in the FeatureTable

**Comment by connormanning** [comment]
Added stubs for batch table support [here](https://github.com/connormanning/entwine/blob/master/entwine/formats/cesium/batch-table.cpp).  You'd probably also need to pass a reference to `entwine::Metadata` into the `cesium::Tile` constructor to get access to the reprojection.  To achieve what you want, it seems to me that you'd need to manually specify an input projection with `-r` when you run `entwine build`, and then reproject the points back to their original projection in the `BatchTable` to gather your stats in the native projection.

**Comment by zhenyanghua** [comment]
Is there an instruction on how to build a batch table into the cesium format?
