### ISSUE TITLE
PDAL pipelines

### ISSUE THREAD

**Issue by LHolst** [connormanning/entwine#60]
what do you think about integrating pdal pipelines?

for now i preprocess DataIN with a PDAL pipeline and then build with entwine
* DataIN -> PDAL pipeline -> Data -> Entwine build -> Output

maybe it is possible to cut the intermediate data
* DataIN -> Entwine build with PDAL pipeline -> Output

**Comment by connormanning** [comment]
It's possible, but there are potential complications.  For example, entwine makes assumptions about the data from its headers that might not be true if the data were to traverse through an arbitrary PDAL pipeline.  PDAL pipelines are also not necessarily linear, and might not be streamable - so the execution logic may get complicated compared to the current flow, which is quite limited.

That said, I think the modifications needed would be pretty well constrained - `Executor::preview` and `Executor::run` would contain most of the execution changes, as well as the configuration flow through the `ConfigParser` to accept a pipeline.
