### ISSUE TITLE
work poor with poor machine

### ISSUE THREAD

**Issue by GHolk** [connormanning/entwine#61]
Excuse me, I user entwine to index about 6G data, with my 5 year old notebook.
I limit docker only 3G memory, or docker would drain my memory.
but it has not finish after 12 hour, only output 166M data, and only message:

    Adding 0 - gcp0824.las
            Pushes complete - joining...

my command:

    docker run -it -v /home/data:/home/data -u 1000 \
        --cpus=2 -m 3g --oom-kill-disable \
        connormanning/entwine build -t 4 -f \
            -i /home/data/gcp0824.las -o /home/data/ncku

does my computer so poor?
how many memory i need to deal with 6G data?
my notebook has only 4G memory.

by the way, it take about 40s to index sample data.

**Comment by GHolk** [comment]
sorry for disturbing, our team already reduce 
the size of point cloud to 200M, so i can index it in 1 minute.

now i try using it with config file cesium.json, 
but it throw error:

    Exception in pool task: No default SRS supplied, and none inferred
    Cannot use this scale for these bounds
    Encountered an error: filters.transformation: Too few entries in transformation matrix: 0 (should be 16)
    Exiting.

how can i fix it?
thx

**Comment by connormanning** [comment]
Since your data does not have spatial reference information, you will need to supply it for your source data using `-r 《your_spatial_reference》EPSG:4978`.

**Comment by GHolk** [comment]
it's seem to I receive point cloud which has no geo location data.
can i output cesium 3d tile which has no geo location, too?
or i would ask my team provide data with geo location...

**Comment by connormanning** [comment]
Cesium renders data on a globe - it needs global position.  Either in the data itself or specified as I mentioned before.

**Comment by GHolk** [comment]
thanks for your help
