### ISSUE TITLE
entwine 1.1.0 build fails - jsoncpp issues

### ISSUE THREAD

**Issue by adamsteer** [connormanning/entwine#62]
Entwine 1.1.0 is failing to build on :
- centos 7
- gcc 4.8.5 (and 6.2.1)

with dependences: 
- PDAL (master) in /usr/local, built from source
- jsoncpp 1.8.0 in /usr/local, built from source

First error:

```/local/build/entwine/entwine/third/arbiter/arbiter.cpp: In lambda function:
/local/build/entwine/entwine/third/arbiter/arbiter.cpp:2609:47: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
         if (BIO* bio = BIO_new_mem_buf(s.data(), -1))
```

...and then, using -fpermissive:
```
[ 98%] Linking CXX executable entwine
/usr/bin/ld: warning: libjsoncpp.so.11, needed by /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../libpdal_base.so, may conflict with libjsoncpp.so.0
/usr/bin/ld: CMakeFiles/kernel.dir/build.cpp.o: undefined reference to symbol '_ZN4Json5ValueC1Em'
/usr/local/lib64/libjsoncpp.so.11: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [kernel/entwine] Error 1
make[1]: *** [kernel/CMakeFiles/kernel.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Not sure what this means. I can't remove centos default jsoncpp, I figured placing a newer version in /usr/local would be the fix - PDAL is linked against the newer jsoncpp just fine.

Advice appreciated!

**Comment by connormanning** [comment]
Is it possible for you to make a Dockerfile based on centos/centos7 that reproduces this?  Presuming you already have some script that gets you from a fresh centos -> building Entwine.  This would make it much easier to fix this and keep things working for centos moving forward.

**Comment by adamsteer** [comment]
OK, good plan - will do. thanks!

**Comment by tjarmane** [comment]
I'm quite new to this, but I'm wondering if this is a similar issue:

running in python

`>>> import docker
>>> client =  docker.DockerClient(version = '1.24')
>>> client.containers.run("connormanning/entwine", "-it -v $HOME:$HOME connormanning/entwine build -i https://entwine.io/sample-data/red-rocks.laz -o ~/dev")

'Invalid kernel type\n\tVersion: 1.1.0\n\tUsage: entwine <kernel> <options>\n\tKernels:\n\t\tbuild\n\t\t\tBuild (or continue to build) an index\n\t\tinfer\n\t\t\tAggregate information for an unindexed dataset\n\t\tmerge\n\t\t\tMerge colocated previously built subsets\n\n'`

**Comment by hobu** [comment]
Doesn't Docker mix stderr and stdout?

**Comment by connormanning** [comment]
This looks like a separate issue from this ticket.  I'm also not sure what the stderr/stdout question is in reference to.

Anyway, I don't think your `client.containers.run` call is correct, looking at the [docs](https://docker-py.readthedocs.io/en/stable/containers.html) it looks like there are function parameters to `run` for the `-it` and `-v` flags you've placed in the command string.  However I've never used `docker-py` so I am just guessing.

I'd think you want something more like:
```
client.containers.run(
    "connormanning/entwine",
    "build -i https://entwine.io/sample-data/red-rocks.laz -o /dev/something",
    tty = True,
    volumes = {'~': {'bind': '/dev', 'mode': 'rw'}}
)
```

I'd recommend getting your command working in regular Docker before migrating it programmatically to `docker-py`:
```
docker run -it -v $HOME:$HOME connormanning/entwine \
    build -i https://entwine.io/sample-data/red-rocks.laz -o ~/dev/red-rocks
```

If the above works properly, then the issue is the Python code.

**Comment by tjarmane** [comment]
Thank you Connor. Got it running easily in Docker from the command line. Need to take a deeper look into the docker-py docs, I think the python code is the source of my problems (still learning the whole docker setup)

**Comment by tjarmane** [comment]
Scratch that, I was able to process the red-rocks data before, but am finding a new error message:
`docker run -it -v $HOME:$HOME connormanning/entwine build -i https://entwine.io/sample-data/red-rocks.laz -o ~/entwine/test
Performing dataset inference...
1 / 1: https://entwine.io/sample-data/red-rocks.laz
Exception in pool task: Could not read from entwine.io/sample-data/red-rocks.laz
Cannot use this scale for these bounds
Encountered an error: Zero points found
Exiting.
`

**Comment by connormanning** [comment]
Looks like your internet connection might have cut out?  That error indicates a failed `GET` request - but that call is working fine for me.  If you see that error often you could download the file locally to remove HTTP calls from your build phase.

**Comment by tjarmane** [comment]
Aha...could not read = failed GET = bad connection.

Just got it working again. Thank you for your huge help - saved me hours of headaches today
