### ISSUE TITLE
Error attempting to read multiple inputs from S3

### ISSUE THREAD

**Issue by gbivins** [connormanning/entwine#65]
I tried running entwine on AWS, where I had multiple files in an S3 bucket and I received this error  
`Encountered an error: Unexpected contents in AWS response`  
When I changed entwine to run against each file in the bucket individually, they worked fine.  What I expected, was that entwine would build it's indexing for all the files in the bucket. This was the behavior I think I remember seeing when running entwine on my local machine. I think I need to use merge but I'm a little confused on how to do it. I'm running this as a DC/OS job which essentially just runs the docker command for building with entwine.  
Does entwine support processing of multiple files in a single location within an S3 bucket?

**Comment by connormanning** [comment]
This workflow should be supported without needing to do anything special.  I'm not sure what the issue is.  Can you try running with environment variable `VERBOSE=1`?  This will dump lots of libcurl output, which should help identify the issue.

**Comment by gbivins** [comment]
Attached. 
[entwine.s3.std.err.txt](https://github.com/connormanning/entwine/files/1310743/entwine.s3.std.err.txt)
[entwine.s3.std.out.txt](https://github.com/connormanning/entwine/files/1310744/entwine.s3.std.out.txt)

**Comment by connormanning** [comment]
Looks like this is an issue with the instance-profile credential initialization in the S3 driver.  I'll see if I can reproduce the issue - what type of EC2 instance are you running when you encounter this?  And are both the EC2 instance and S3 data in `us-east-1`?

**Comment by gbivins** [comment]
I'm running on m4.2xlarge. The bucket and the instance are in us-east-1 (N. Virginia)

**Comment by gbivins** [comment]
@connormanning were you able to reproduce this? Do you need anymore info from me?

**Comment by connormanning** [comment]
I have reproduced the issue - haven't yet determined the reason for it.

**Comment by connormanning** [comment]
I've pushed a fix for this - repull your docker image and give it another try.

**Comment by gbivins** [comment]
@connormanning Works like a champ!
