### ISSUE TITLE
Ignore the Z Axis in bounds?

### ISSUE THREAD

**Issue by Hisol** [connormanning/entwine#67]
I would like to be able to specify a bound in X & Y but not specify, or have ignored the Z limitations.  Is this possible or something that can be easily implemented?  Currently I am specifying large positive and negative Z bounds to ensure all data is captured, and whilst I doubt I will be processing data for any mountain ranges any time soon, it doesn't feel like the right approach?

Thanks

**Comment by connormanning** [comment]
This is currently not possible, and a bit difficult conceptually since Entwine always starts with a cube for equal resolution in each spatial dimension.  Can you give some information about your workflow - are you trying to specify bounds early on and add continually add data to the index later on?

**Comment by Hisol** [comment]
Exactly that, I am indexing data but I wish to add to that data index later on.  Ideally I'd rather not assume nothing higher or lower will be encountered, but if the initial set is quite flat then it could quite easily occur.  At this point I am manually tweaking the Z to be something like -10000 and 10000 to try and ensure future captures will reside within the index bounds.  Would be nice if it were possible to ignore the Z axis limits.

**Comment by connormanning** [comment]
I don't think this capability is feasible for the sake of simplicity of the new EPT format.  I suggest stretching the Zs like you have, or using multiple resources since the renderers can handle that just fine.
