### ISSUE TITLE
Build dependency versions are not documented

### ISSUE THREAD

**Issue by tushar-dadlani** [connormanning/entwine#71]
I noticed when I am trying to build entwine on my local machine, I don't know what dependencies I need and at what versions. I need to read the CMake file to understand them. It would be good to have them documented.

**Comment by connormanning** [comment]
I'm a bit torn on this since Entwine's only real dependency is PDAL 1.7 or later, although of course PDAL build configuration bleeds into the capabilities you get with Entwine.  So I think I'd like to be hands-off about this one and push responsibility for it upstream to PDAL.
