### ISSUE TITLE
Cesium 3D tiles. Docker stops in joining step

### ISSUE THREAD

**Issue by linkas** [connormanning/entwine#72]
Hello,
For last few days I was working with this amazing tool to convert lidar data to cesium 3D tiles. By doing that i have successfully converted demo data "red-rocks.laz" to the cesium format, but when i changed input to the my data i have faced one issue and i cant find out how to solve it. Problem is  that when i start to run docker it goes to joining step and then just shut down the process without error messages.
Bellow i have attached screenshots from my docker window and screenshot with my data information from lasinfo window.
![docker-toolbox-window](https://user-images.githubusercontent.com/23637693/33210494-c339d918-d11a-11e7-8557-4da76dc27320.jpg)
![lasinfo_01](https://user-images.githubusercontent.com/23637693/33210495-c34e70da-d11a-11e7-81fc-643561f0abe8.jpg)
![lasinfo_02](https://user-images.githubusercontent.com/23637693/33210496-c363ab94-d11a-11e7-8487-d4f0c3d44320.jpg)

Can you please help me to solve this issue?

**Comment by connormanning** [comment]
If you can attach this file - or email it to me - I can take a look.

**Comment by linkas** [comment]
Here is my files. silo_25833.laz is original file. silo_out2_25833.laz is
re projected . After i had problem whit original file I have transformed
coordinates system by using PDAL 1.6 library.

I am very new to these thinks. Thank you very much in advance for your help.

Best regards
Linas​
 silo_25833.laz
<https://drive.google.com/file/d/1KhVjLsxh5sNpPcE6TeZqFPExgUN0j7dr/view?usp=drive_web>
​​
 silo_out2_25833.laz
<https://drive.google.com/file/d/1kvAGY2g3EB8WLsi-Zu5dXiQjQvaAmZRY/view?usp=drive_web>
​

2017-11-24 16:41 GMT+01:00 Connor Manning <notifications@github.com>:

**Comment by connormanning** [comment]
When I build this file with the `cesium.json` configuration, I get lots of errors like this:
`Exception in pool task: Unable to fetch data and convert as requested: Red:uint16_t(41891) -> unsigned char`

This means that your file has 16-bit color values, which must be scaled down.  You should use the `cesium-truncated.json` configuration, which performs this scaling for you.  I'm not sure why these errors aren't printed for you, but the truncated configuration works for me for your `silo_25833.laz` file:

<img width="1272" alt="screen shot 2017-11-24 at 11 50 37 am" src="https://user-images.githubusercontent.com/5015470/33220454-1f7730ca-d10e-11e7-9f2c-61e35e794ab1.png">

**Comment by linkas** [comment]
thank you very much.
one more question. How can I use cesium-truncated.json ? I should download
it as a file to use instead cesium.json ?

2017-11-24 18:54 GMT+01:00 Connor Manning <notifications@github.com>:

**Comment by connormanning** [comment]
It's already there in the same location as the `cesium.json` file you used before.  So you will use `build /var/entwine/config/cesium-truncated.json` in your invocation.

**Comment by linkas** [comment]
I have tried cesium-truncated.json but result was the same :( i have
attached screenshot with code and result.

I also have tried manually by using Lastools to reduce color value from
16bit to 8bit  (-scale_rgb_down : divides all RGB values by 256 (to go from
16 bit to 8 bit numbers) but it also did not help.

Maybe you have some another suggestion ho to fix it? :(

Thx in advance


2017-11-24 19:03 GMT+01:00 Connor Manning <notifications@github.com>:

**Comment by connormanning** [comment]
Usually when a docker build with entwine exits with no visible errors it's because the VM ran out of memory.  I'm not familiar with docker on Windows, but I assume there's somewhere in the UI where you can specify the allowable memory for docker - you might try increasing that a bit.

**Comment by linkas** [comment]
Hi,
As you assumed problem was in VM memory. I have increased it and know its
working perfectly.

Thank you so mach for your help.

Br
Linas

2017-11-30 19:49 GMT+01:00 Connor Manning <notifications@github.com>:
