### ISSUE TITLE
CMake Error - Export Unknown Arguments

### ISSUE THREAD

**Issue by Sciencegeek123** [connormanning/entwine#8]
Trying to build locally, and getting the following:
```
root@ip-172-31-25-29:~/src/entwine/makefiles# cmake -G "Unix Makefiles" ../
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.35.0")
CMake Error at CMakeLists.txt:68 (export):
  export Unknown arguments.


-- Configuring incomplete, errors occurred!
See also "/root/src/entwine/makefiles/CMakeFiles/CMakeOutput.log".
See also "/root/src/entwine/makefiles/CMakeFiles/CMakeError.log".
```

**Comment by connormanning** [comment]
I suspect an outdated CMake, but I'm not very familiar with everything that's going on in this file.  It seems likely that the `cmake_minimum_required` declaration isn't correct anymore and might need to be increased.  Can you post your `cmake --version` output?  `3.5.2` is what I'm using.

Something to try might be replacing line 66 in `CMakeLists.txt` with `install(TARGETS entwine DESTINATION lib)`, and then removing the lines after that.  Those changes correspond to an older version of the file without some of the export stuff.

**Comment by Sciencegeek123** [comment]
You may be right about the version, I'm at cmake version 2.8.12.2.

Replacing line 66 didn't resolve. :(

**Comment by Sciencegeek123** [comment]
Updating to the latest cmake build did resolve the CMakeLists issue, however now I'm getting compilation issues. Unsure if they are related / on my end yet.

**Comment by Sciencegeek123** [comment]
Note for @connormanning , I resolved my compilation issues by updating to gcc/g++ 6. It appears the bug that was causing my issue _may_ have been resolved in 5 though. Searching the "max_align_t" error should yield more information about the error if interested.
