### ISSUE TITLE
Process Files outside $HOME

### ISSUE THREAD

**Issue by matzora** [connormanning/entwine#80]
I'm trying to use Entwine to process very big LAS file and i don't have enough disk space in my $HOME to copy in the LAS before I give it to entwine docker.

How can I give LAS file from an hard drive to Entwine Docker ?

Thanks.

**Comment by connormanning** [comment]
See the [docs for volume mapping in docker](https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v-read-only).
