### ISSUE TITLE
Support deleting existing index

### ISSUE THREAD

**Issue by bhavin266** [connormanning/entwine#83]
I wanted to know if entwine supports index deletion. If one keeps indexing point cloud additively, at some point it is bound have large point density. Is there a way to remove index ( say based on time or source files) in such cases?

**Comment by connormanning** [comment]
This is not currently possible and there are not plans to add this functionality at this time.  What is your use-case for continually adding to a single resource?  In general it is recommended that you would index your data such that each "logical unit" of data (e.g. a portion you would want to be able to selectively enable/disable) would be created as its own resource.

Both potree and speck.ly support multi-resource rendering and selective toggling of individual resources:

http://speck.ly/?s=http://cache.greyhound.io&r=iowa-z,mn-z
http://potree.entwine.io/data/custom.html?r=["iowa-z","mn-z"]

**Comment by swarvanusanyal** [comment]
We have two use cases. 

1. We collect lidar point cloud in a particular area in many iteration and want to index it as soon as it comes to our cloud infra structure. That is why we want to add new point cloud data to existing indexes.
2. We also would like to expire point cloud information that is collected yeara ago. Hence we were exploring possibilities of deleting certain logical unit of indexes. 

I think the solution you are proposing it, we can put every logical unit of the point cloud in separate output directory and use a comma separated list of directory in greyhound while rendering. And whenever certain logical unit of cloud expires, just remove it from the directory list while rendering using greyhound. Am I right?

**Comment by connormanning** [comment]
Correct, that's my proposed solution.  It could get a bit messy if you are managing tons of small resources, but it scales better to large-scale data collections and makes caching behavior much more predictable than continually adding to single resources.

**Comment by adamsteer** [comment]
I second Connor here - we treat a ‘survey’ or ‘mission’ as a logical unit, with the basic proposition that we let entwine do what it is great at (indexing) - and handle the rest (what gets shown or not) with existing web/data management stuff

**Comment by bhavin266** [comment]
Really appreciate your inputs. The approach you guys are suggesting makes sense. Closing this issue.
