### ISSUE TITLE
entwine demo datasets down

### ISSUE THREAD

**Issue by tomvantilburg** [connormanning/entwine#86]
Just a heads-up, seems to be a CORS problem?

`Failed to load http://cache.greyhound.io/resource/dk-z/info: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://potree.entwine.io' is therefore not allowed access. The response had HTTP status code 504.`

**Comment by connormanning** [comment]
Thanks for this update - new datasets are currently up at potree.entwine.io in the EPT format (see #98).
