### ISSUE TITLE
Encountered an error: Couldn't create subset

### ISSUE THREAD

**Issue by aleksandrmelnyk** [connormanning/entwine#87]
hi all,
am trying to merge 64 subsets (which were generated ok with -s 1..64), but merge failed:
```
Overlaps: 31
Merging 56 / 64
Overlaps: 31
Merging 57 / 64
Overlaps: 34
Merging 58 / 64
Merging 59 / 64
Create failed: 58
Encountered an error: Couldn't create subset
Exiting.
```
Any ideas what could it be? May be any way to get more verbose error message?

cheers,

Alex.

**Comment by connormanning** [comment]
Looks like a metadata file for that subset may be missing or has unexpected contents.  Not sure why that would happen unless that subset portion failed to complete, but it's probably a missing `entwine-57` file.  I'd probably have to look at the data to see what's wrong - I don't think there's any hooks for a better error message at this time.  Not much that can be done except to re-build that subset.

**Comment by aleksandrmelnyk** [comment]
ok, thanks. That happened for dataset where laz files were disjoint or overlapping. For dataset where laz files are adjacent it worked fine
