### ISSUE TITLE
Always print 100%,but not completed

### ISSUE THREAD

**Issue by dlliyang** [connormanning/entwine#89]
T: 2,200s P: 808M/h A: 76,546,048 U: 52% C: 71 H: 5 I: 494,179,032 P: 100%
 T: 2,210s P: 807M/h A: 76,546,048 U: 54% C: 75 H: 5 I: 495,440,600 P: 100%
 T: 2,220s P: 804M/h A: 76,546,048 U: 52% C: 70 H: 5 I: 496,053,820 P: 100%
 T: 2,230s P: 800M/h A: 76,546,048 U: 41% C: 57 H: 5 I: 496,053,820 P: 100%
 T: 2,240s P: 797M/h A: 76,546,048 U: 27% C: 38 H: 5 I: 496,053,820 P: 100%
 T: 2,250s P: 793M/h A: 76,546,048 U: 15% C: 20 H: 5 I: 496,053,820 P: 100%
	Done 46
 T: 2,260s P: 790M/h A: 76,546,048 U: 3% C: 2 H: 5 I: 496,053,820 P: 100%
Saving hierarchy...
Saving registry...
Exception in pool task: Unable to fetch data and convert as requested: Blue:uint16_t(256) -> unsigned char

![screenshot from 2018-05-29 17-08-23](https://user-images.githubusercontent.com/26989316/40649243-fe3956c6-6362-11e8-8b88-374e91d5d7dd.png)

this is my cesium.json
{
     "threads": 8,
    "reprojection": {
	"in" :"EPSG:4978",
        "out" : "EPSG:4978"
    },    
    "formats": {
        "cesium": {
            "tilesetSplit":16,
            "geometricErrorDivisor": 16.0
        }
    }
}

**Comment by connormanning** [comment]
You'll need to scale your color values to 8-bit.  See #26.
