### ISSUE TITLE
how to create more depth tiles?

### ISSUE THREAD

**Issue by wemamawe** [connormanning/entwine#90]
hello sir:
I have a 100+billion points data, and want to convert Cesium format, i have try many parameters(tilesetSplit,baseDepth,coldDepth), but always get the same tiles . there are many big tiles for internet service, if i want to split lidar data to small tile. what should i do?

![2018-05-30 09-47-36](https://user-images.githubusercontent.com/29365634/40694634-0a544adc-63f0-11e8-837a-0666100adfd7.jpg)

**Comment by connormanning** [comment]
See #98 for the latest on entwine/cesium interaction.  Check out the configuration docs and the EPT format doc to see how to control the output.

**Comment by wemamawe** [comment]
hello sir .
 sorry to trouble you,  i still can't resolve those problem. I had upload my data to BaiDu Cloud, you can download it and have a look.
data url : https://pan.baidu.com/s/1Nf-V6Y1iuPykclnC1zMUmQ
passward : v9ez
Expect you have a good result.



在 2018-06-26 03:13:19，"Connor Manning" <notifications@github.com> 写道：


Closed #90.

**Comment by wemamawe** [comment]
hello sir .
 sorry to trouble you,  i still can't resolve those problem. I had upload my data to BaiDu Cloud, you can download it and have a look.
data url :https://pan.baidu.com/s/1zanR5LmBNRCi0Kto5_cq0A
passward : zkmi
The projection of this data is UTM50N.
Expect you have a good result.



在 2018-06-26 03:13:19，"Connor Manning" <notifications@github.com> 写道：


Closed #90.
