### ISSUE TITLE
Help with setting up entwine in ubuntu

### ISSUE THREAD

**Issue by ghost** [connormanning/entwine#91]
I'm having issues running a build command with the docker build of entwine. I've tried some variations of mkdir ~/entwine
docker run -it -v $HOME:/opt/data connormanning/entwine \
    build -i /opt/data/abc.laz -o /opt/data/entwine/abc
but cannot get the build function to from my specified local paths or urls. I'm wondering what the -it, -v, and $HOME:/ syntax signify? Is $HOME a path? I'm not accustomed to running docker and not familiar with these command line flags.

**Comment by adamsteer** [comment]
@kmercy287 check out https://docs.docker.com/edge/engine/reference/commandline/run/#options

the -v flag tells docker ‘I want to map a volume’; which you then define using `local_path:/path/inside/container’. The docker container will then see whatever you have at the local path, at the path you’ve defined for a container, eg for  `$HOME:/opt/data`:

local: 
$HOME/things/file.laz

inside docker container:
/opt/data/things/file.laz

It’s really just setting an alias for docker to use internally.

for your example to work, you need to make sure your abc.laz file is located at ~/abc.laz (or $HOME/abc.laz) on your local filesystem.

Also check that $HOME has a value - type `echo $HOME` to see what it’s value is. If it has none, use `docker run` with a full path like:

`docker run -it -v /home/username/my-lazfiles:/opt/data connromanning/entwine …. `

HTH

**Comment by connormanning** [comment]
I'll close this one as it's more of a Docker usage issue and Adam has it pretty well covered (thanks Adam!).  The README is a bit too UNIX-specific so perhaps that should be made more general.
