### ISSUE TITLE
 entwine build -i  /xxxxx/red-rocks.laz  -o /xxxxxx/entwine Get some errors

### ISSUE THREAD

**Issue by zhan520** [connormanning/entwine#95]
![image](https://user-images.githubusercontent.com/12770958/41387973-5d4cfd74-6fbc-11e8-9514-d1087ac85679.png)
Got error 11
*** Error in `entwine': free(): invalid pointer: 0x00007f02ac005a78 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f02bf8df7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f02bf8e837a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f02bf8ec53c]
/usr/local/lib/libentwine.so.2(_ZN4pdal5StageD1Ev+0x1cb)[0x7f02c0c1372b]
/usr/local/lib/libpdal_base.so.6(_ZN4pdal9LasWriterD1Ev+0x25a)[0x7f02bf05f44e]
/usr/local/lib/libentwine.so.2(_ZNK7entwine13LasZipStorage5writeERNS_5ChunkE+0x1ede)[0x7f02c0c0512e]
/usr/local/lib/libentwine.so.2(_ZN7entwine9BaseChunk4saveEv+0x73)[0x7f02c0c56313]
/usr/local/lib/libentwine.so.2(_ZNK7entwine4Cold4saveERKNS_7arbiter8EndpointE+0x67)[0x7f02c0c66a17]
/usr/local/lib/libentwine.so.2(_ZN7entwine7Builder4saveERKNS_7arbiter8EndpointE+0x6f)[0x7f02c0c4d9bf]
/usr/local/lib/libentwine.so.2(_ZN7entwine7Builder5doRunEm+0x316)[0x7f02c0c4dd76]
/usr/local/lib/libentwine.so.2(+0xf8ec0)[0x7f02c0c4dec0]
/usr/local/lib/libentwine.so.2(_ZN7entwine4Pool4workEv+0x1ce)[0x7f02c0ccfd8e]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80)[0x7f02c0209c80]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f02bdf626ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f02bf96f41d]

**Comment by zhan520** [comment]
![image](https://user-images.githubusercontent.com/12770958/41388036-a30fbaea-6fbc-11e8-96d0-543c28183c51.png)
MAC get almost the same error

**Comment by connormanning** [comment]
This was due to a conflicting install of openssl in the alpine dockerfile (needs to be libressl which is installed upstream).  Fixed.
