### ISSUE TITLE
How to merge two and more tileset.json files into one tileset.json file?

### ISSUE THREAD

**Issue by spatialhast** [connormanning/entwine#97]
I have two datasets (pnts and tileset.json file) generated by entwine tool. How I can merge two existing tileset.json files (and corresponded pnts files) into one (without generating new dataset from two sourse las files) for using as one layer in Cesium?
It is possible or I need generate new dataset from source las files?

thanks!

**Comment by connormanning** [comment]
This is possible at the Cesium level - it's beyond the scope of Entwine.  You would need to make a tileset that contains no data itself, but rather points to your two tilesets.  See: https://github.com/AnalyticalGraphicsInc/3d-tiles#external-tilesets

**Comment by dremonkey** [comment]
In case someone comes across this... the location of the external-tilests documentation has moved to https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#external-tilesets
